from __future__ import annotations

import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pytest

from src.search_eval.approved_policy import (
    export_approved_skillopt_policy,
    split_retrieval_evaluation_record,
)
from src.search_eval.continuous_optimizer import (
    append_reward_memory_entry,
    build_live_canary_handoff,
    build_next_iteration_seed,
    build_optimizer_decision_record,
    run_continuous_optimization_iteration,
    validate_continuous_iteration_manifest,
    validate_continuous_iteration_summary,
    validate_evaluator_contract_v1,
    validate_live_canary_handoff,
    validate_next_iteration_seed,
    validate_optimizer_decision_record,
    validate_optimizer_run_id,
    validate_reward_memory_entry,
)
from src.search_eval.retrieval_eval import (
    build_fixture_retrieval_results,
    score_retrieval_results,
)
from src.search_eval.release_holdout import (
    RELEASE_HOLDOUT_AUTHORITY_CONTEXT_ENV,
    ReleaseHoldoutAggregate,
    evaluate_release_holdout,
    write_release_holdout_manifest,
)
from src.search_eval.skillopt_adapter import canonical_file_hash
from src.search_eval.skillopt_contract import ValidationError, load_json
from src.search_eval.skillopt_materializer import materialize_skillopt_search_benchmark
from tests.fixtures.release_holdout_authority import release_manifest_payload
from tests.skillopt_acceptance_fixtures import publish_accepted_candidate

DATASET = "data/search_eval/skillopt_paper_search_v0.json"
CONTROL = "data/search_eval/skillopt_execution_control_v0.json"
BASELINE_SKILL = "docs/skillopt_search/baseline_skill.md"


@pytest.fixture(autouse=True)
def _scope_release_holdout_authority_env(monkeypatch: pytest.MonkeyPatch):
    """Prevent authority context generated by a fixture from leaking across tests."""
    monkeypatch.delenv(RELEASE_HOLDOUT_AUTHORITY_CONTEXT_ENV, raising=False)
    yield


def _materialization_manifest_path(tmp_path: Path) -> Path:
    manifest = materialize_skillopt_search_benchmark(
        output_dir=tmp_path / "materialized",
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
    )
    return Path(manifest["output_dir"]) / "skillopt_materialization_manifest.json"


def _candidate_best_skill(tmp_path: Path) -> Path:
    baseline = Path(BASELINE_SKILL).read_text(encoding="utf-8")
    text = (
        baseline
        + """

## SkillOpt accepted edit — continuous RL memory candidate
- QueryAnalyzer standard search path should preserve exact paper-title and author intent first.
- Do not enable `use_llm_search` for this policy.
- Do not enable HyDE prompt optimization for this policy.
- Do not promote RelevanceFilter prompt optimization for this policy.
- Prefer source_queries that place must-include title phrases before broad acceptable synonyms.
"""
    )
    tmp_path.mkdir(parents=True, exist_ok=True)
    path = tmp_path / "best_skill.md"
    path.write_text(text, encoding="utf-8")
    return path


def _evals(best_skill: Path | None = None) -> tuple[dict, dict]:
    baseline_eval = score_retrieval_results(
        dataset_path=DATASET,
        results_by_query=build_fixture_retrieval_results(
            dataset_path=DATASET, quality="baseline"
        ),
    )
    candidate_eval = score_retrieval_results(
        dataset_path=DATASET,
        results_by_query=build_fixture_retrieval_results(
            dataset_path=DATASET, quality="candidate"
        ),
    )
    baseline_eval = {
        **baseline_eval,
        "evaluated_skill_hash": canonical_file_hash(BASELINE_SKILL),
    }
    if best_skill is not None:
        candidate_eval = {
            **candidate_eval,
            "evaluated_skill_hash": canonical_file_hash(best_skill),
        }
    return baseline_eval, candidate_eval


def _two_stage_eval_inputs(
    baseline_eval: dict,
    candidate_eval: dict,
    *,
    tmp_path: Path,
    best_skill: Path,
) -> dict:
    dataset = load_json(DATASET)
    selection_ids = [
        query["query_id"]
        for query in dataset["queries"]
        if query["split"] == "selection"
    ]
    selection_baseline = split_retrieval_evaluation_record(baseline_eval, selection_ids)
    selection_candidate = split_retrieval_evaluation_record(
        candidate_eval, selection_ids
    )

    def load_release_holdout():
        from src.search_eval import approved_policy as approved_policy_module

        selection_gate = approved_policy_module._build_selection_gate_evidence(
            dataset=dataset,
            candidate_eval=selection_candidate,
            baseline_eval_hash=approved_policy_module._mapping_hash(selection_baseline),
            candidate_eval_hash=approved_policy_module._mapping_hash(
                selection_candidate
            ),
        )
        manifest = write_release_holdout_manifest(
            tmp_path / "release_manifest.json",
            release_manifest_payload(
                tmp_path,
                generation_id="optimizer-fixture:generation-1",
                object_version="optimizer-fixture-object:v1",
                issuer_identity="optimizer-fixture-release-authority:v1",
                evaluator_identity="optimizer-fixture-release-evaluator:v1",
            ),
        )
        return evaluate_release_holdout(
            manifest=manifest,
            state_root=tmp_path / "release_state",
            baseline_sha256=canonical_file_hash(BASELINE_SKILL),
            candidate_sha256=canonical_file_hash(best_skill),
            thresholds={"ndcg_delta": 0.01, "safety": 1.0},
            evaluator_identity="optimizer-fixture-release-evaluator:v1",
            contract_identity="retrieval-eval:v1",
            nonce="optimizer-fixture-nonce-1",
            selection_evidence={
                **selection_gate,
                "baseline_skill_hash": canonical_file_hash(BASELINE_SKILL),
                "candidate_skill_hash": canonical_file_hash(best_skill),
            },
            evaluator=lambda _: ReleaseHoldoutAggregate(
                sample_count=12,
                metrics={"ndcg_delta": 0.02, "safety": 1.0},
                threshold_results={"ndcg_delta": True, "safety": True},
            ),
        )

    return {
        "selection_baseline_eval": selection_baseline,
        "selection_candidate_eval": selection_candidate,
        "release_holdout_evaluation_loader": load_release_holdout,
    }


def _approved_policy(tmp_path: Path) -> tuple[dict, dict, dict, Path, Path]:
    best_skill = _candidate_best_skill(tmp_path)
    baseline_eval, candidate_eval = _evals(best_skill)
    manifest_path = _materialization_manifest_path(tmp_path)
    accepted = publish_accepted_candidate(
        parent=tmp_path,
        best_skill_path=best_skill,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
    )
    artifact = export_approved_skillopt_policy(
        **accepted,
        output_dir=tmp_path / "approved",
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
        **_two_stage_eval_inputs(
            baseline_eval, candidate_eval, tmp_path=tmp_path, best_skill=best_skill
        ),
        minimum_ndcg_delta=0.01,
    )
    return (
        artifact,
        baseline_eval,
        candidate_eval,
        manifest_path,
        Path(artifact["artifact_path"]),
    )


def _decision(tmp_path: Path, **overrides):
    artifact, baseline_eval, candidate_eval, manifest_path, _artifact_path = (
        _approved_policy(tmp_path)
    )
    return build_optimizer_decision_record(
        run_id="run-20260704-accepted",
        approved_policy_artifact=artifact,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
        **overrides,
    )


def test_evaluator_contract_requires_minimum_ndcg_delta():
    baseline_eval = score_retrieval_results(
        dataset_path=DATASET,
        results_by_query=build_fixture_retrieval_results(
            dataset_path=DATASET, quality="candidate"
        ),
    )
    candidate_eval = dict(baseline_eval)

    with pytest.raises(ValidationError, match="candidate nDCG@10"):
        validate_evaluator_contract_v1(
            baseline_eval=baseline_eval, candidate_eval=candidate_eval
        )


def test_optimizer_decision_updates_reward_memory_only_after_approval(tmp_path: Path):
    artifact, baseline_eval, candidate_eval, manifest_path, _artifact_path = (
        _approved_policy(tmp_path)
    )
    decision = build_optimizer_decision_record(
        run_id="run-20260704-accepted",
        approved_policy_artifact=artifact,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
    )
    validate_optimizer_decision_record(decision)

    selection_reward = round(
        artifact["metric_snapshot"]["candidate"]
        - artifact["metric_snapshot"]["baseline"],
        6,
    )
    full_record_reward = round(candidate_eval["nDCG@10"] - baseline_eval["nDCG@10"], 6)
    assert selection_reward != full_record_reward
    assert decision["reward"] == selection_reward

    memory_path = tmp_path / "reward-memory.jsonl"
    entry = append_reward_memory_entry(
        memory_path, decision, approved_policy_artifact_path=_artifact_path
    )

    assert entry["skill_hash"] == decision["candidate_skill_hash"]
    assert entry["reward"] >= 0.01
    lines = memory_path.read_text(encoding="utf-8").splitlines()
    assert len(lines) == 1
    assert json.loads(lines[0])["run_id"] == "run-20260704-accepted"


def test_optimizer_decision_retains_only_narrow_approval_receipt(tmp_path: Path):
    decision = _decision(tmp_path)
    receipt = decision.approval_receipt

    assert not hasattr(decision, "approved_policy")
    assert receipt.runtime_default_off is True
    assert receipt.skill_hash == decision["candidate_skill_hash"]
    assert receipt.baseline_hash == decision["baseline_hash"]
    assert receipt.dataset_hash == decision["dataset_hash"]
    assert receipt.execution_control_hash == decision["execution_control_hash"]
    assert receipt.rollback_skill_hash == decision["rollback_to"]["skill_hash"]
    serialized = json.dumps(receipt.__dict__, sort_keys=True, default=str)
    for forbidden in (
        "release_holdout_gate",
        "generation_id",
        "evaluator",
        "threshold",
        "metric_snapshot",
        "capability",
    ):
        assert forbidden not in serialized


def test_optimizer_rejects_raw_approved_policy_mapping(tmp_path: Path) -> None:
    artifact, baseline_eval, candidate_eval, manifest_path, _ = _approved_policy(
        tmp_path
    )

    with pytest.raises(ValidationError, match="raw mappings|fully revalidated"):
        build_optimizer_decision_record(
            run_id="run-raw-approval",
            approved_policy_artifact=dict(artifact),
            baseline_eval=baseline_eval,
            candidate_eval=candidate_eval,
            dataset_path=DATASET,
            control_path=CONTROL,
            baseline_skill_path=BASELINE_SKILL,
        )


def test_next_seed_and_reward_reject_raw_decision_mapping(tmp_path: Path) -> None:
    artifact, baseline_eval, candidate_eval, manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )
    decision = build_optimizer_decision_record(
        run_id="run-raw-decision",
        approved_policy_artifact=artifact,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
    )
    raw = dict(decision)

    with pytest.raises(ValidationError, match="fully validated"):
        build_next_iteration_seed(raw)
    with pytest.raises(ValidationError, match="fully validated"):
        append_reward_memory_entry(
            tmp_path / "reward-memory.jsonl",
            raw,
            approved_policy_artifact_path=artifact_path,
        )


def test_reward_memory_rejects_rolled_back_or_quarantined_runs(tmp_path: Path):
    with pytest.raises(ValidationError, match="rolled back or quarantined"):
        append_reward_memory_entry(
            tmp_path / "memory.jsonl",
            _decision(tmp_path / "rolled", status="accepted", rolled_back=True),
            approved_policy_artifact_path=_approved_policy(tmp_path / "rolled")[4],
        )

    with pytest.raises(ValidationError, match="rolled back or quarantined"):
        append_reward_memory_entry(
            tmp_path / "memory.jsonl",
            _decision(tmp_path / "quarantined", status="accepted", quarantined=True),
            approved_policy_artifact_path=_approved_policy(tmp_path / "quarantined")[4],
        )


def test_optimizer_rejects_eval_payload_hash_drift_after_approval(tmp_path: Path):
    artifact, baseline_eval, candidate_eval, manifest_path, _artifact_path = (
        _approved_policy(tmp_path)
    )
    baseline_drifts = [
        {
            **baseline_eval,
            "scoring_elapsed_ms": baseline_eval["scoring_elapsed_ms"] + 0.001,
        },
        {**baseline_eval, "artifact_path": "hidden-extra-field"},
    ]
    for drifted_baseline in baseline_drifts:
        with pytest.raises(ValidationError, match="baseline_eval hash"):
            build_optimizer_decision_record(
                run_id="run-baseline-eval-drift",
                approved_policy_artifact=artifact,
                baseline_eval=drifted_baseline,
                candidate_eval=candidate_eval,
                dataset_path=DATASET,
                control_path=CONTROL,
                baseline_skill_path=BASELINE_SKILL,
            )

    candidate_drifts = [
        {
            **candidate_eval,
            "scoring_elapsed_ms": candidate_eval["scoring_elapsed_ms"] + 0.001,
        },
        {**candidate_eval, "runtime_env_path": "hidden-extra-field"},
    ]
    for drifted_candidate in candidate_drifts:
        with pytest.raises(ValidationError, match="candidate_eval hash"):
            build_optimizer_decision_record(
                run_id="run-candidate-eval-drift",
                approved_policy_artifact=artifact,
                baseline_eval=baseline_eval,
                candidate_eval=drifted_candidate,
                dataset_path=DATASET,
                control_path=CONTROL,
                baseline_skill_path=BASELINE_SKILL,
            )


def test_reward_memory_rejects_duplicate_artifact_even_with_new_run_id(tmp_path: Path):
    artifact, baseline_eval, candidate_eval, manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )
    decision = build_optimizer_decision_record(
        run_id="run-duplicate-a",
        approved_policy_artifact=artifact,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
    )
    memory_path = tmp_path / "reward-memory.jsonl"
    append_reward_memory_entry(
        memory_path, decision, approved_policy_artifact_path=artifact_path
    )
    duplicate_decision = build_optimizer_decision_record(
        run_id="run-duplicate-b",
        approved_policy_artifact=artifact,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
    )

    with pytest.raises(ValidationError, match="duplicate approved artifact"):
        append_reward_memory_entry(
            memory_path, duplicate_decision, approved_policy_artifact_path=artifact_path
        )


def test_reward_memory_concurrent_duplicate_is_one_locked_append(tmp_path: Path):
    artifact, baseline_eval, candidate_eval, manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )
    decision = build_optimizer_decision_record(
        run_id="run-concurrent-duplicate",
        approved_policy_artifact=artifact,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
    )
    memory_path = tmp_path / "concurrent-reward-memory.jsonl"

    def append_once():
        try:
            append_reward_memory_entry(
                memory_path, decision, approved_policy_artifact_path=artifact_path
            )
            return "appended"
        except ValidationError as exc:
            return str(exc)

    with ThreadPoolExecutor(max_workers=2) as executor:
        results = list(executor.map(lambda _index: append_once(), range(2)))

    assert results.count("appended") == 2
    assert len(memory_path.read_text(encoding="utf-8").splitlines()) == 1


def test_reward_memory_rejects_forged_approved_artifact_hash(tmp_path: Path):
    artifact, baseline_eval, candidate_eval, manifest_path, _artifact_path = (
        _approved_policy(tmp_path)
    )
    decision = build_optimizer_decision_record(
        run_id="run-20260704-accepted",
        approved_policy_artifact=artifact,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
    )
    forged_path = tmp_path / "forged" / "approved_policy_artifact.json"
    forged_path.parent.mkdir()
    forged_path.write_text(
        json.dumps({**artifact, "dataset_hash": "forged-dataset"}), encoding="utf-8"
    )

    with pytest.raises(
        ValidationError,
        match="file hash mismatch|dataset[_ ]hash|canonical sibling|accepted provenance",
    ):
        append_reward_memory_entry(
            tmp_path / "memory.jsonl",
            decision,
            approved_policy_artifact_path=forged_path,
        )


def test_optimizer_blocks_eval_hash_mismatch(tmp_path: Path):
    artifact, baseline_eval, candidate_eval, manifest_path, _artifact_path = (
        _approved_policy(tmp_path / "hash")
    )
    bad_eval = {**candidate_eval, "evaluated_skill_hash": "sha256:" + "0" * 64}
    with pytest.raises(ValidationError, match="evaluated_skill_hash"):
        build_optimizer_decision_record(
            run_id="run-hash-mismatch",
            approved_policy_artifact=artifact,
            baseline_eval=baseline_eval,
            candidate_eval=bad_eval,
            dataset_path=DATASET,
            control_path=CONTROL,
            baseline_skill_path=BASELINE_SKILL,
        )


def test_optimizer_rejects_baseline_and_materialization_lineage_drift(tmp_path: Path):
    artifact, baseline_eval, candidate_eval, manifest_path, _artifact_path = (
        _approved_policy(tmp_path)
    )
    wrong_baseline = tmp_path / "wrong-baseline.md"
    wrong_baseline.write_text(
        Path(BASELINE_SKILL).read_text(encoding="utf-8") + "\nextra drift\n",
        encoding="utf-8",
    )

    with pytest.raises(ValidationError, match="baseline_skill_path"):
        build_optimizer_decision_record(
            run_id="run-baseline-drift",
            approved_policy_artifact=artifact,
            baseline_eval=baseline_eval,
            candidate_eval=candidate_eval,
            dataset_path=DATASET,
            control_path=CONTROL,
            baseline_skill_path=wrong_baseline,
        )

    with pytest.raises(TypeError, match="materialization_manifest_path"):
        build_optimizer_decision_record(
            run_id="run-manifest-drift",
            approved_policy_artifact=artifact,
            baseline_eval=baseline_eval,
            candidate_eval=candidate_eval,
            dataset_path=DATASET,
            control_path=CONTROL,
            baseline_skill_path=BASELINE_SKILL,
            materialization_manifest_path=manifest_path,
        )


def test_next_iteration_seed_uses_only_previous_approved_policy_as_baseline(
    tmp_path: Path,
):
    decision = _decision(tmp_path)

    seed = build_next_iteration_seed(decision)

    assert seed["baseline_hash"] == decision["candidate_skill_hash"]
    assert seed["baseline_source"] == "approved_policy_export"
    assert (
        seed["reward_memory_file_anchor"]
        == decision["approved_policy_artifact_file_hash"]
    )
    assert seed["release_holdout_feedback_included"] is False
    assert seed["release_evaluation_managed_externally"] is True


def test_next_iteration_seed_rejects_non_accepted_decision(tmp_path: Path):
    decision = _decision(tmp_path)
    rejected = {**decision, "status": "rejected", "reward": 0.0}

    with pytest.raises(ValidationError, match="accepted optimizer decision"):
        build_next_iteration_seed(rejected)


def test_next_iteration_seed_rejects_tampered_operating_contract(tmp_path: Path):
    decision = _decision(tmp_path)
    seed = build_next_iteration_seed(decision)

    from src.search_eval.continuous_optimizer import validate_next_iteration_seed

    with pytest.raises(ValidationError, match="baseline_source"):
        validate_next_iteration_seed({**seed, "baseline_source": "manual_override"})
    with pytest.raises(ValidationError, match="reward_memory_file_anchor"):
        validate_next_iteration_seed(
            {**seed, "reward_memory_file_anchor": "not-a-digest"}
        )
    with pytest.raises(ValidationError, match="scope"):
        validate_next_iteration_seed({**seed, "scope": "hyde_prompt_promotion"})
    with pytest.raises(ValidationError, match="unsupported fields"):
        validate_next_iteration_seed(
            {**seed, "holdout_reuse_policy": "reuse_test_for_training"}
        )
    with pytest.raises(ValidationError, match="exclude external release feedback"):
        validate_next_iteration_seed(
            {**seed, "release_holdout_feedback_included": True}
        )


def test_run_continuous_optimization_iteration_writes_operating_artifacts(
    tmp_path: Path,
):
    artifact, baseline_eval, candidate_eval, manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )
    approval = {
        "approved_by": "search-quality-owner",
        "approved_at": artifact["created_at"],
        "expires_at": "2999-01-01T00:00:00Z",
        "artifact_hash": canonical_file_hash(artifact_path),
    }

    result = run_continuous_optimization_iteration(
        run_id="run-iteration-001",
        output_root=tmp_path / "runs",
        approved_policy_artifact_path=artifact_path,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
        reward_memory_path=tmp_path / "reward-memory.jsonl",
        manual_approval=approval,
        rollback_sla_minutes=15,
    )

    validate_continuous_iteration_manifest(result["manifest"])
    assert Path(result["manifest_path"]).exists()
    assert Path(result["manifest"]["decision_record_path"]).exists()
    assert Path(result["manifest"]["reward_memory_entry_path"]).exists()
    assert Path(result["manifest"]["next_iteration_seed_path"]).exists()
    assert Path(result["manifest"]["live_canary_handoff_path"]).exists()
    assert result["decision"]["run_id"] == "run-iteration-001"
    assert (
        result["reward_entry"]["skill_hash"]
        == result["decision"]["candidate_skill_hash"]
    )
    assert (
        result["next_iteration_seed"]["baseline_hash"]
        == result["decision"]["candidate_skill_hash"]
    )
    assert result["live_canary_handoff"]["rollout_fraction"] == 0.0
    assert (tmp_path / "reward-memory.jsonl").read_text(encoding="utf-8").count(
        "run-iteration-001"
    ) == 1

    optimizer_outputs = {
        key: value.persisted_record() if hasattr(value, "persisted_record") else value
        for key, value in result.items()
        if key not in {"manifest_path", "summary_path"}
    }
    serialized = json.dumps(optimizer_outputs, sort_keys=True)
    for release_secret in (
        "optimizer-fixture:generation-1",
        "optimizer-fixture-object:v1",
        "optimizer-fixture-release-authority:v1",
        "optimizer-fixture-release-evaluator:v1",
        "retrieval-eval:v1",
        "optimizer-fixture-nonce-1",
    ):
        assert release_secret not in serialized
    _assert_no_release_feedback_keys(optimizer_outputs)

    tampered_manifest = {
        **result["manifest"],
        "decision_record_hash": "sha256:" + "0" * 64,
    }
    with pytest.raises(ValidationError, match="decision_record hash mismatch"):
        validate_continuous_iteration_manifest(tampered_manifest)
    with pytest.raises(ValidationError, match="version"):
        validate_continuous_iteration_manifest(
            {
                **result["manifest"],
                "version": "skillopt-continuous-iteration-manifest-v0",
            }
        )
    with pytest.raises(ValidationError, match="version"):
        validate_continuous_iteration_summary(
            {
                **result["summary"],
                "version": "skillopt-continuous-iteration-summary-v0",
            }
        )

    replay = run_continuous_optimization_iteration(
        run_id="run-iteration-001",
        output_root=tmp_path / "replay-runs",
        approved_policy_artifact_path=artifact_path,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
        reward_memory_path=tmp_path / "reward-memory.jsonl",
    )
    assert replay["reward_entry"] == result["reward_entry"]
    assert (
        len((tmp_path / "reward-memory.jsonl").read_text(encoding="utf-8").splitlines())
        == 1
    )


def test_run_continuous_optimization_iteration_requires_complete_canary_inputs(
    tmp_path: Path,
):
    _artifact, baseline_eval, candidate_eval, manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )

    with pytest.raises(ValidationError, match="manual_approval"):
        run_continuous_optimization_iteration(
            run_id="run-iteration-no-approval",
            output_root=tmp_path / "runs",
            approved_policy_artifact_path=artifact_path,
            baseline_eval=baseline_eval,
            candidate_eval=candidate_eval,
            dataset_path=DATASET,
            control_path=CONTROL,
            baseline_skill_path=BASELINE_SKILL,
            reward_memory_path=tmp_path / "reward-memory.jsonl",
            rollback_sla_minutes=15,
        )


def test_run_continuous_optimization_iteration_does_not_append_on_downstream_failure(
    tmp_path: Path,
):
    _artifact, baseline_eval, candidate_eval, manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )
    reward_memory = tmp_path / "reward-memory.jsonl"

    with pytest.raises(ValidationError, match="manual_approval"):
        run_continuous_optimization_iteration(
            run_id="bad-canary",
            output_root=tmp_path / "runs",
            approved_policy_artifact_path=artifact_path,
            baseline_eval=baseline_eval,
            candidate_eval=candidate_eval,
            dataset_path=DATASET,
            control_path=CONTROL,
            baseline_skill_path=BASELINE_SKILL,
            reward_memory_path=reward_memory,
            rollback_sla_minutes=15,
        )

    assert not reward_memory.exists()


def test_iteration_stages_outputs_before_reward_append_and_retry_succeeds(
    tmp_path: Path, monkeypatch
):
    _artifact, baseline_eval, candidate_eval, manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )
    reward_memory = tmp_path / "reward-memory.jsonl"
    output_root = tmp_path / "runs"
    from src.search_eval import continuous_optimizer as optimizer_module

    original_write = optimizer_module._exclusive_atomic_write_at

    def fail_reward_entry(lease, name, payload):
        if name == "reward_memory_entry.json":
            raise OSError("forced staged artifact failure")
        return original_write(lease, name, payload)

    monkeypatch.setattr(
        optimizer_module, "_exclusive_atomic_write_at", fail_reward_entry
    )
    with pytest.raises(OSError, match="forced staged artifact failure"):
        run_continuous_optimization_iteration(
            run_id="retryable-run",
            output_root=output_root,
            approved_policy_artifact_path=artifact_path,
            baseline_eval=baseline_eval,
            candidate_eval=candidate_eval,
            dataset_path=DATASET,
            control_path=CONTROL,
            baseline_skill_path=BASELINE_SKILL,
            reward_memory_path=reward_memory,
        )
    assert not reward_memory.exists()

    monkeypatch.setattr(optimizer_module, "_exclusive_atomic_write_at", original_write)
    result = run_continuous_optimization_iteration(
        run_id="retryable-run",
        output_root=tmp_path / "retry-runs",
        approved_policy_artifact_path=artifact_path,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
        reward_memory_path=reward_memory,
    )
    assert result["manifest"]["status"] == "complete"
    assert len(reward_memory.read_text(encoding="utf-8").splitlines()) == 1


@pytest.mark.parametrize(
    "run_id",
    [
        "",
        ".",
        "..",
        "/absolute",
        "../escape",
        "a/b",
        r"a\b",
        "has space",
        "control\nvalue",
        "ＦＵＬＬＷＩＤＴＨ",
        "café",
        "a" * 129,
    ],
)
def test_optimizer_run_id_rejects_path_and_unicode_tricks(run_id: str):
    with pytest.raises(ValidationError, match="run_id"):
        validate_optimizer_run_id(run_id)


def test_optimizer_output_rejects_root_intermediate_and_run_symlinks(
    tmp_path: Path,
):
    _artifact, baseline_eval, candidate_eval, _manifest_path, artifact_path = (
        _approved_policy(tmp_path / "fixture")
    )
    outside = tmp_path / "outside"
    outside.mkdir()
    sentinel = outside / "sentinel.txt"
    sentinel.write_text("unchanged", encoding="utf-8")

    root_link = tmp_path / "root-link"
    root_link.symlink_to(outside, target_is_directory=True)
    intermediate = tmp_path / "safe"
    intermediate.mkdir()
    (intermediate / "link").symlink_to(outside, target_is_directory=True)
    real_root = tmp_path / "real-runs"
    real_root.mkdir()
    (real_root / "run-symlink").symlink_to(outside, target_is_directory=True)

    common = {
        "approved_policy_artifact_path": artifact_path,
        "baseline_eval": baseline_eval,
        "candidate_eval": candidate_eval,
        "dataset_path": DATASET,
        "control_path": CONTROL,
        "baseline_skill_path": BASELINE_SKILL,
        "reward_memory_path": tmp_path / "reward-memory.jsonl",
    }
    for run_id, output_root in (
        ("root-link-run", root_link),
        ("intermediate-run", intermediate / "link" / "runs"),
        ("run-symlink", real_root),
    ):
        with pytest.raises(ValidationError, match="symlink|directory|already exists"):
            run_continuous_optimization_iteration(
                run_id=run_id, output_root=output_root, **common
            )
    assert sentinel.read_text(encoding="utf-8") == "unchanged"


@pytest.mark.parametrize("attack", ["root", "run", "file", "file-preexisting"])
def test_optimizer_output_inode_leases_reject_aba_without_touching_outside(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, attack: str
):
    from src.search_eval import continuous_optimizer as optimizer_module

    _artifact, baseline_eval, candidate_eval, _manifest_path, artifact_path = (
        _approved_policy(tmp_path / "fixture")
    )
    output_root = tmp_path / "runs"
    outside = tmp_path / "outside"
    outside.mkdir()
    sentinel = outside / "sentinel.txt"
    sentinel.write_text("unchanged", encoding="utf-8")
    original = optimizer_module._exclusive_atomic_write_at
    attacked = False

    def attack_before_write(lease, name, payload):
        nonlocal attacked
        if not attacked and (attack != "file" or name == "next_iteration_seed.json"):
            attacked = True
            if attack == "root":
                lease.root_path.rename(tmp_path / "displaced-root")
                lease.root_path.mkdir()
            elif attack == "run":
                (lease.root_path / lease.run_id).rename(tmp_path / "displaced-run")
                (lease.root_path / lease.run_id).mkdir()
            elif attack == "file":
                decision = lease.root_path / lease.run_id / "optimizer_decision.json"
                decision.unlink()
                decision.symlink_to(sentinel)
            else:
                (lease.root_path / lease.run_id / name).symlink_to(sentinel)
        return original(lease, name, payload)

    monkeypatch.setattr(
        optimizer_module, "_exclusive_atomic_write_at", attack_before_write
    )
    with pytest.raises(ValidationError, match="changed|contained|lease|already exists"):
        run_continuous_optimization_iteration(
            run_id=f"aba-{attack}",
            output_root=output_root,
            approved_policy_artifact_path=artifact_path,
            baseline_eval=baseline_eval,
            candidate_eval=candidate_eval,
            dataset_path=DATASET,
            control_path=CONTROL,
            baseline_skill_path=BASELINE_SKILL,
            reward_memory_path=tmp_path / "reward-memory.jsonl",
        )
    assert sentinel.read_text(encoding="utf-8") == "unchanged"


def test_reward_memory_rejects_forged_reward_value(tmp_path: Path):
    artifact, baseline_eval, candidate_eval, manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )
    decision = build_optimizer_decision_record(
        run_id="run-forged-reward",
        approved_policy_artifact=artifact,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
    )
    forged = {**decision, "reward": 999.0}

    with pytest.raises(ValidationError, match="reward"):
        append_reward_memory_entry(
            tmp_path / "memory.jsonl",
            forged,
            approved_policy_artifact_path=artifact_path,
        )


def test_live_canary_handoff_requires_manual_approval_and_stale_hash_check(
    tmp_path: Path,
):
    _artifact, _baseline_eval, _candidate_eval, _manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )
    approval = {
        "approved_by": "search-quality-owner",
        "approved_at": _artifact["created_at"],
        "expires_at": "2999-01-01T00:00:00Z",
        "artifact_hash": canonical_file_hash(artifact_path),
    }

    handoff = build_live_canary_handoff(
        approved_policy_artifact_path=artifact_path,
        manual_approval=approval,
        rollback_sla_minutes=15,
    )
    validate_live_canary_handoff(handoff)
    assert handoff["rollout_fraction"] == 0.0
    assert handoff["state"] == "manual_approval_required_before_enablement"

    substituted_path = {
        **handoff,
        "runtime_env": {
            **handoff["runtime_env"],
            "SKILLOPT_SEARCH_POLICY_PATH": str(
                (tmp_path / "other-policy.md").resolve()
            ),
        },
    }
    with pytest.raises(ValidationError, match="approved runtime_policy_path"):
        validate_live_canary_handoff(substituted_path)

    substituted_hash = {
        **handoff,
        "runtime_env": {
            **handoff["runtime_env"],
            "SKILLOPT_SEARCH_POLICY_HASH": "sha256:" + "f" * 64,
        },
    }
    with pytest.raises(ValidationError, match="approved skill hash"):
        validate_live_canary_handoff(substituted_hash)

    tampered_sla = {**handoff, "rollback_sla_minutes": 999}
    with pytest.raises(ValidationError, match="rollback_sla"):
        validate_live_canary_handoff(tampered_sla)

    expired_handoff = {
        **handoff,
        "created_at": "2026-07-04T13:00:00Z",
        "manual_approval": {
            **handoff["manual_approval"],
            "approved_at": "1999-01-01T00:00:00Z",
            "expires_at": "2000-01-01T00:00:00Z",
        },
    }
    with pytest.raises(ValidationError, match="stale|expiry"):
        validate_live_canary_handoff(expired_handoff)

    stale_time = {**approval, "approved_at": "1999-01-01T00:00:00Z"}
    with pytest.raises(ValidationError, match="stale"):
        build_live_canary_handoff(
            approved_policy_artifact_path=artifact_path,
            manual_approval=stale_time,
            rollback_sla_minutes=15,
        )

    stale = {**approval, "artifact_hash": "sha256:" + "0" * 64}
    with pytest.raises(ValidationError, match="stale"):
        build_live_canary_handoff(
            approved_policy_artifact_path=artifact_path,
            manual_approval=stale,
            rollback_sla_minutes=15,
        )

    with pytest.raises(ValidationError, match="rollback_sla"):
        build_live_canary_handoff(
            approved_policy_artifact_path=artifact_path,
            manual_approval=approval,
            rollback_sla_minutes=120,
        )


def test_optimizer_v0_contracts_and_removed_generation_api_fail_closed(
    tmp_path: Path,
) -> None:
    decision = _decision(tmp_path)
    seed = build_next_iteration_seed(decision)
    reward = append_reward_memory_entry(
        tmp_path / "v0-memory.jsonl",
        decision,
        approved_policy_artifact_path=decision.approval_receipt.artifact_path,
    )
    artifact_path = _approved_policy(tmp_path / "canary")[4]
    artifact = json.loads(artifact_path.read_text(encoding="utf-8"))
    approval = {
        "approved_by": "search-quality-owner",
        "approved_at": artifact["created_at"],
        "expires_at": "2999-01-01T00:00:00Z",
        "artifact_hash": canonical_file_hash(artifact_path),
    }
    handoff = build_live_canary_handoff(
        approved_policy_artifact_path=artifact_path,
        manual_approval=approval,
        rollback_sla_minutes=15,
    )

    with pytest.raises(ValidationError, match="version"):
        validate_optimizer_decision_record(
            {
                **decision.persisted_record(),
                "version": "skillopt-continuous-optimizer-record-v0",
            }
        )
    with pytest.raises(ValidationError, match="version"):
        validate_next_iteration_seed(
            {**seed, "version": "skillopt-next-iteration-seed-v0"}
        )
    with pytest.raises(ValidationError, match="version"):
        validate_live_canary_handoff(
            {**handoff, "version": "skillopt-live-canary-handoff-v0"}
        )
    with pytest.raises(ValidationError, match="version"):
        validate_reward_memory_entry(
            {**reward, "version": "skillopt-reward-memory-entry-v0"}
        )
    with pytest.raises(TypeError, match="next_holdout_generation_id"):
        build_next_iteration_seed(decision, next_holdout_generation_id="forbidden")


def test_optimizer_visible_nested_schemas_reject_hostile_aliases(tmp_path: Path):
    artifact, baseline_eval, candidate_eval, _manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )
    decision = build_optimizer_decision_record(
        run_id="hostile-schema-run",
        approved_policy_artifact=artifact,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
    )
    seed = build_next_iteration_seed(decision)
    reward = append_reward_memory_entry(
        tmp_path / "hostile-memory.jsonl",
        decision,
        approved_policy_artifact_path=artifact_path,
    )
    approval = {
        "approved_by": "search-quality-owner",
        "approved_at": artifact["created_at"],
        "expires_at": "2999-01-01T00:00:00Z",
        "artifact_hash": canonical_file_hash(artifact_path),
    }
    handoff = build_live_canary_handoff(
        approved_policy_artifact_path=artifact_path,
        manual_approval=approval,
        rollback_sla_minutes=15,
    )
    result = run_continuous_optimization_iteration(
        run_id="hostile-summary-run",
        output_root=tmp_path / "hostile-runs",
        approved_policy_artifact_path=artifact_path,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
        reward_memory_path=tmp_path / "hostile-iteration-memory.jsonl",
    )

    with pytest.raises(KeyError):
        _ = decision["safety"]["labels"]
    with pytest.raises(ValidationError, match="safety schema"):
        validate_optimizer_decision_record(
            {
                **decision.persisted_record(),
                "safety": {**decision["safety"], "La-BeLs": ["private"]},
            }
        )
    with pytest.raises(ValidationError, match="unsupported fields"):
        validate_reward_memory_entry({**reward, "PerQuery": {"q": 1}})
    with pytest.raises(ValidationError, match="unsupported fields"):
        validate_next_iteration_seed({**seed, "GENERATION-ID": "private"})
    with pytest.raises(ValidationError, match="manual_approval schema"):
        validate_live_canary_handoff(
            {
                **handoff,
                "manual_approval": {
                    **handoff["manual_approval"],
                    "ReLeAsE-DeTaIlS": {"rankings": []},
                },
            }
        )
    with pytest.raises(ValidationError, match="unsupported fields"):
        validate_continuous_iteration_manifest(
            {**result["manifest"], "holdoutDetails": {"secrets": "x"}}
        )
    with pytest.raises(ValidationError, match="reward_memory schema"):
        validate_continuous_iteration_summary(
            {
                **result["summary"],
                "reward_memory": {
                    **result["summary"]["reward_memory"],
                    "PROMPTS": ["private"],
                },
            }
        )


def test_terminal_manifest_publishes_only_after_exactly_once_reward_commit(
    tmp_path: Path, monkeypatch
):
    from src.search_eval import continuous_optimizer as optimizer_module

    _artifact, baseline_eval, candidate_eval, _manifest_path, artifact_path = (
        _approved_policy(tmp_path)
    )
    output_root = tmp_path / "terminal-runs"
    reward_memory = tmp_path / "terminal-order-memory.jsonl"
    original_write_output_json = optimizer_module._write_or_verify_output_json
    failed_once = False

    def fail_first_terminal_manifest(lease, name, value):
        nonlocal failed_once
        if name == "continuous_iteration_manifest.json" and not failed_once:
            failed_once = True
            raise OSError("forced terminal manifest publication failure")
        return original_write_output_json(lease, name, value)

    monkeypatch.setattr(
        optimizer_module, "_write_or_verify_output_json", fail_first_terminal_manifest
    )
    with pytest.raises(OSError, match="terminal manifest publication"):
        run_continuous_optimization_iteration(
            run_id="terminal-order-run",
            output_root=output_root,
            approved_policy_artifact_path=artifact_path,
            baseline_eval=baseline_eval,
            candidate_eval=candidate_eval,
            dataset_path=DATASET,
            control_path=CONTROL,
            baseline_skill_path=BASELINE_SKILL,
            reward_memory_path=reward_memory,
        )

    assert not (
        output_root / "terminal-order-run" / "continuous_iteration_manifest.json"
    ).exists()
    assert len(reward_memory.read_text(encoding="utf-8").splitlines()) == 1

    replay = run_continuous_optimization_iteration(
        run_id="terminal-order-run",
        output_root=output_root,
        approved_policy_artifact_path=artifact_path,
        baseline_eval=baseline_eval,
        candidate_eval=candidate_eval,
        dataset_path=DATASET,
        control_path=CONTROL,
        baseline_skill_path=BASELINE_SKILL,
        reward_memory_path=reward_memory,
    )
    assert replay["manifest"]["status"] == "complete"
    assert len(reward_memory.read_text(encoding="utf-8").splitlines()) == 1


@pytest.mark.parametrize(
    "failed_artifact",
    [
        "continuous_iteration_transaction.json",
        "optimizer_decision.json",
        "next_iteration_seed.json",
        "reward_memory_entry.json",
        "reward_memory_commit.json",
        "continuous_iteration_summary.json",
        "continuous_iteration_manifest.json",
    ],
)
def test_same_run_directory_recovers_each_publication_boundary_exactly_once(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, failed_artifact: str
) -> None:
    from src.search_eval import continuous_optimizer as optimizer_module

    _artifact, baseline_eval, candidate_eval, _manifest_path, artifact_path = (
        _approved_policy(tmp_path / "fixture")
    )
    output_root = tmp_path / "runs"
    reward_memory = tmp_path / "reward-memory.jsonl"
    original_write = optimizer_module._write_output_json
    original_resume_write = optimizer_module._write_or_verify_output_json
    failed = False

    def fail_initial_write(lease, name, value):
        nonlocal failed
        if name == failed_artifact and not failed:
            failed = True
            raise OSError(f"forced boundary failure: {name}")
        return original_write(lease, name, value)

    def fail_resumable_write(lease, name, value):
        nonlocal failed
        if name == failed_artifact and not failed:
            failed = True
            raise OSError(f"forced boundary failure: {name}")
        return original_resume_write(lease, name, value)

    monkeypatch.setattr(optimizer_module, "_write_output_json", fail_initial_write)
    monkeypatch.setattr(
        optimizer_module, "_write_or_verify_output_json", fail_resumable_write
    )
    common = {
        "run_id": "same-directory-boundary-run",
        "output_root": output_root,
        "approved_policy_artifact_path": artifact_path,
        "baseline_eval": baseline_eval,
        "candidate_eval": candidate_eval,
        "dataset_path": DATASET,
        "control_path": CONTROL,
        "baseline_skill_path": BASELINE_SKILL,
        "reward_memory_path": reward_memory,
    }
    with pytest.raises(OSError, match="forced boundary failure"):
        run_continuous_optimization_iteration(**common)

    monkeypatch.setattr(optimizer_module, "_write_output_json", original_write)
    monkeypatch.setattr(
        optimizer_module, "_write_or_verify_output_json", original_resume_write
    )
    recovered = run_continuous_optimization_iteration(**common)

    assert recovered["manifest"]["status"] == "complete"
    assert Path(recovered["manifest_path"]).exists()
    assert len(reward_memory.read_text(encoding="utf-8").splitlines()) == 1


def test_same_run_directory_recovers_after_reward_append_before_commit(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from src.search_eval import continuous_optimizer as optimizer_module

    _artifact, baseline_eval, candidate_eval, _manifest_path, artifact_path = (
        _approved_policy(tmp_path / "fixture")
    )
    output_root = tmp_path / "runs"
    reward_memory = tmp_path / "reward-memory.jsonl"
    original_append = optimizer_module._append_reward_memory_entry_value
    failed = False

    def append_then_fail(path, entry):
        nonlocal failed
        committed = original_append(path, entry)
        if not failed:
            failed = True
            raise OSError("forced failure after reward append")
        return committed

    monkeypatch.setattr(
        optimizer_module, "_append_reward_memory_entry_value", append_then_fail
    )
    common = {
        "run_id": "post-append-recovery-run",
        "output_root": output_root,
        "approved_policy_artifact_path": artifact_path,
        "baseline_eval": baseline_eval,
        "candidate_eval": candidate_eval,
        "dataset_path": DATASET,
        "control_path": CONTROL,
        "baseline_skill_path": BASELINE_SKILL,
        "reward_memory_path": reward_memory,
    }
    with pytest.raises(OSError, match="after reward append"):
        run_continuous_optimization_iteration(**common)
    assert len(reward_memory.read_text(encoding="utf-8").splitlines()) == 1

    monkeypatch.setattr(
        optimizer_module, "_append_reward_memory_entry_value", original_append
    )
    recovered = run_continuous_optimization_iteration(**common)

    assert recovered["manifest"]["status"] == "complete"
    assert len(reward_memory.read_text(encoding="utf-8").splitlines()) == 1


def test_same_run_directory_rejects_conflicting_retry(tmp_path: Path, monkeypatch) -> None:
    from src.search_eval import continuous_optimizer as optimizer_module

    artifact, baseline_eval, candidate_eval, _manifest_path, artifact_path = (
        _approved_policy(tmp_path / "fixture")
    )
    output_root = tmp_path / "runs"
    reward_memory = tmp_path / "reward-memory.jsonl"
    original_write = optimizer_module._write_or_verify_output_json

    def fail_manifest(lease, name, value):
        if name == "continuous_iteration_manifest.json":
            raise OSError("forced incomplete transaction")
        return original_write(lease, name, value)

    monkeypatch.setattr(optimizer_module, "_write_or_verify_output_json", fail_manifest)
    common = {
        "run_id": "conflicting-retry-run",
        "output_root": output_root,
        "approved_policy_artifact_path": artifact_path,
        "baseline_eval": baseline_eval,
        "candidate_eval": candidate_eval,
        "dataset_path": DATASET,
        "control_path": CONTROL,
        "baseline_skill_path": BASELINE_SKILL,
        "reward_memory_path": reward_memory,
    }
    with pytest.raises(OSError, match="incomplete transaction"):
        run_continuous_optimization_iteration(**common)
    monkeypatch.setattr(optimizer_module, "_write_or_verify_output_json", original_write)

    approval = {
        "approved_by": "search-quality-owner",
        "approved_at": artifact["created_at"],
        "expires_at": "2999-01-01T00:00:00Z",
        "artifact_hash": canonical_file_hash(artifact_path),
    }
    with pytest.raises(ValidationError, match="transaction does not match retry"):
        run_continuous_optimization_iteration(
            **common, manual_approval=approval, rollback_sla_minutes=15
        )
    assert len(reward_memory.read_text(encoding="utf-8").splitlines()) == 1


def test_concurrent_same_directory_retry_completes_once(tmp_path: Path, monkeypatch) -> None:
    from src.search_eval import continuous_optimizer as optimizer_module

    _artifact, baseline_eval, candidate_eval, _manifest_path, artifact_path = (
        _approved_policy(tmp_path / "fixture")
    )
    output_root = tmp_path / "runs"
    reward_memory = tmp_path / "reward-memory.jsonl"
    original_write = optimizer_module._write_or_verify_output_json

    def fail_manifest(lease, name, value):
        if name == "continuous_iteration_manifest.json":
            raise OSError("seed incomplete transaction")
        return original_write(lease, name, value)

    common = {
        "run_id": "concurrent-recovery-run",
        "output_root": output_root,
        "approved_policy_artifact_path": artifact_path,
        "baseline_eval": baseline_eval,
        "candidate_eval": candidate_eval,
        "dataset_path": DATASET,
        "control_path": CONTROL,
        "baseline_skill_path": BASELINE_SKILL,
        "reward_memory_path": reward_memory,
    }
    monkeypatch.setattr(optimizer_module, "_write_or_verify_output_json", fail_manifest)
    with pytest.raises(OSError, match="seed incomplete transaction"):
        run_continuous_optimization_iteration(**common)
    monkeypatch.setattr(optimizer_module, "_write_or_verify_output_json", original_write)

    with ThreadPoolExecutor(max_workers=2) as executor:
        results = list(
            executor.map(
                lambda _: run_continuous_optimization_iteration(**common), range(2)
            )
        )

    assert results[0]["manifest"] == results[1]["manifest"]
    assert len(reward_memory.read_text(encoding="utf-8").splitlines()) == 1


@pytest.mark.parametrize("tamper", ["unexpected", "missing", "symlink", "duplicate"])
def test_same_run_directory_recovery_rejects_inconsistent_evidence(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, tamper: str
) -> None:
    from src.search_eval import continuous_optimizer as optimizer_module

    _artifact, baseline_eval, candidate_eval, _manifest_path, artifact_path = (
        _approved_policy(tmp_path / "fixture")
    )
    output_root = tmp_path / "runs"
    reward_memory = tmp_path / "reward-memory.jsonl"
    original_write = optimizer_module._write_or_verify_output_json

    def fail_manifest(lease, name, value):
        if name == "continuous_iteration_manifest.json":
            raise OSError("seed tamperable transaction")
        return original_write(lease, name, value)

    common = {
        "run_id": "tamper-recovery-run",
        "output_root": output_root,
        "approved_policy_artifact_path": artifact_path,
        "baseline_eval": baseline_eval,
        "candidate_eval": candidate_eval,
        "dataset_path": DATASET,
        "control_path": CONTROL,
        "baseline_skill_path": BASELINE_SKILL,
        "reward_memory_path": reward_memory,
    }
    monkeypatch.setattr(optimizer_module, "_write_or_verify_output_json", fail_manifest)
    with pytest.raises(OSError, match="seed tamperable transaction"):
        run_continuous_optimization_iteration(**common)
    monkeypatch.setattr(optimizer_module, "_write_or_verify_output_json", original_write)

    run_dir = output_root / common["run_id"]
    sentinel = tmp_path / "outside-sentinel.json"
    sentinel.write_text("{}\n", encoding="utf-8")
    if tamper == "unexpected":
        (run_dir / "unexpected.json").write_text("{}\n", encoding="utf-8")
        error = "unexpected artifacts"
    elif tamper == "missing":
        (run_dir / "optimizer_decision.json").unlink()
        error = "prefix is inconsistent"
    elif tamper == "symlink":
        summary = run_dir / "continuous_iteration_summary.json"
        summary.unlink()
        summary.symlink_to(sentinel)
        error = "unsafe artifact"
    else:
        row = reward_memory.read_text(encoding="utf-8")
        reward_memory.write_text(row + row, encoding="utf-8")
        error = "duplicate matching run entries"

    with pytest.raises(ValidationError, match=error):
        run_continuous_optimization_iteration(**common)
    assert sentinel.read_text(encoding="utf-8") == "{}\n"

def _assert_no_release_feedback_keys(value) -> None:
    forbidden = {
        "release_holdout_gate",
        "holdout_gate",
        "holdout_lineage",
        "generation_id",
        "previous_holdout_generation_id",
        "next_holdout_generation_id",
        "holdout_reuse_policy",
        "release_holdout_capability",
        "release_holdout_capability_path",
        "release_holdout_path",
        "evaluator_identity",
        "contract_identity",
        "metric_snapshot",
        "metrics",
        "thresholds",
        "threshold_results",
        "sample_count",
        "per_query",
        "query_id",
        "queries",
    }
    if isinstance(value, dict):
        assert not forbidden.intersection(value)
        for nested in value.values():
            _assert_no_release_feedback_keys(nested)
    elif isinstance(value, list):
        for nested in value:
            _assert_no_release_feedback_keys(nested)
