"""Freeze public BEIR SciFact candidates before observing either model's scores."""
import csv
import hashlib
import io
import json
from pathlib import Path
import random
import re
import urllib.request
import zipfile
from rank_bm25 import BM25Okapi
from src.search_eval.judged_replay import digest

ROOT = Path(__file__).parent
URL = "https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/scifact.zip"
raw = urllib.request.urlopen(URL, timeout=60).read()
assert hashlib.md5(raw).hexdigest() == "5f7d1de60b170fc8027bb7898e2efca1", "Public archive checksum mismatch"
with zipfile.ZipFile(io.BytesIO(raw)) as archive:
    corpus = [json.loads(line) for line in archive.read("scifact/corpus.jsonl").decode().splitlines()]
    queries = {str(q["_id"]): q["text"] for q in map(json.loads, archive.read("scifact/queries.jsonl").decode().splitlines())}
    qrels = {}
    for row in csv.DictReader(io.StringIO(archive.read("scifact/qrels/test.tsv").decode()), delimiter="\t"):
        qrels.setdefault(row["query-id"], {})[row["corpus-id"]] = int(row["score"])
corpus.sort(key=lambda d: str(d["_id"]))
tokenize = lambda text: re.findall(r"\w+", text.lower())
index = BM25Okapi([tokenize(d["title"]+" "+d["text"]) for d in corpus])
# No selection based on model outcomes or on whether the gold appears in top10.
selected = sorted(random.Random(20260929).sample(sorted(qrels), 8))
rows = []
for qid in selected:
    scores = index.get_scores(tokenize(queries[qid]))
    indices = sorted(range(len(corpus)), key=lambda i: (-float(scores[i]), str(corpus[i]["_id"])))[:10]
    candidates = [{"paper_key": str(corpus[i]["_id"]), "title": corpus[i]["title"], "abstract": corpus[i]["text"]} for i in indices]
    assert all(c["title"].strip() and c["abstract"].strip() and len(c["title"]) <= 1000 and len(c["abstract"]) <= 12000 for c in candidates)
    rows.append({"query_id":qid, "query":queries[qid], "candidates":candidates, "qrels":qrels[qid], "gold_in_pool":sorted(set(qrels[qid]) & {c["paper_key"] for c in candidates})})
report = {"version":"scifact-frozen-pilot-v1", "source":URL, "archive_sha256":hashlib.sha256(raw).hexdigest(), "license":"CC-BY-SA-4.0 per BEIR dataset card", "attribution":"Wadden et al. 2020, Fact or Fiction: Verifying Scientific Claims; Thakur et al. 2021, BEIR", "seed":20260929, "selection":"8 query IDs sampled from sorted BEIR test qrel IDs; English BM25 top10 from all5183 abstracts; no gold injection", "label_provenance":"published SciFact/BEIR qrels, not generated by JEV or this agent", "unjudged_policy":"Unlisted documents score zero only under standard benchmark scoring convention, not certified nonrelevant", "queries":rows}
report["input_hash"] = digest(report)
with (ROOT/"frozen-en.json").open("x") as f:
    json.dump(report,f,ensure_ascii=False,indent=2)
print(json.dumps({"corpus":len(corpus),"test_queries":len(qrels),"selected":[{"query_id":r["query_id"],"query":r["query"],"gold_in_pool":r["gold_in_pool"]} for r in rows]},ensure_ascii=False))
