#!/usr/bin/env python3
"""Validate GEO comparison source data and generate Python/TypeScript projections."""

from __future__ import annotations

import argparse
import ast
import importlib.util
import json
import pprint
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

SOURCE = REPO_ROOT / "data/blog/geo-comparisons.json"
PYTHON_OUTPUT = REPO_ROOT / "routers/geo_comparisons_generated.py"
TYPESCRIPT_OUTPUT = REPO_ROOT / "web-ui/src/seo/geoComparisons.generated.ts"

_HELPER_SPEC = importlib.util.spec_from_file_location(
    "geo_comparisons_contract", REPO_ROOT / "routers/geo_comparisons.py"
)
if _HELPER_SPEC is None or _HELPER_SPEC.loader is None:
    raise RuntimeError("unable to load GEO comparison contract")
_HELPER = importlib.util.module_from_spec(_HELPER_SPEC)
_HELPER_SPEC.loader.exec_module(_HELPER)
canonical_sha256 = _HELPER.canonical_sha256
validate_comparisons = _HELPER.validate_comparisons


def _series_members() -> dict[str, list[str]]:
    tree = ast.parse((REPO_ROOT / "routers/seo.py").read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", None) == "BLOG_SERIES":
            value = ast.literal_eval(node.value)
            return {key: entry["slugs"] for key, entry in value.items()}
    raise ValueError("routers/seo.py does not define literal BLOG_SERIES")


def _published_slugs() -> set[str]:
    raw = json.loads((REPO_ROOT / "data/blog/posts.json").read_text(encoding="utf-8"))
    posts = raw.get("posts", raw) if isinstance(raw, dict) else raw
    return {post["slug"] for post in posts if post.get("published") is True}


def load_source(path: Path = SOURCE) -> dict[str, Any]:
    document = json.loads(
        path.read_text(encoding="utf-8"),
        parse_constant=lambda token: (_ for _ in ()).throw(
            ValueError(f"non-finite JSON constant is forbidden: {token}")
        ),
    )
    comparisons = validate_comparisons(
        document,
        series_members=_series_members(),
        published_slugs=_published_slugs(),
    )
    return {"schema_version": 1, "comparisons": comparisons}


def _python_projection(document: dict[str, Any]) -> str:
    comparisons = pprint.pformat(document["comparisons"], sort_dicts=False, width=100)
    return (
        '"""Generated by scripts/sync_geo_comparisons.py; do not edit."""\n\n'
        f'GEO_COMPARISONS_SOURCE_SHA256 = "{canonical_sha256(document)}"\n'
        f"GEO_COMPARISONS = {comparisons}\n"
    )


def _typescript_projection(document: dict[str, Any]) -> str:
    payload = json.dumps(document["comparisons"], ensure_ascii=False, indent=2)
    digest = canonical_sha256(document)
    return f"""// Generated by scripts/sync_geo_comparisons.py; do not edit.
export type GeoComparisonAxis =
  | 'retrieval_or_representation_unit'
  | 'graph_construction'
  | 'evaluation_context'
  | 'traceability'
  | 'cost'
  | 'failure_conditions';

export interface GeoComparisonCell {{
  state: 'known' | 'unknown' | 'not_applicable';
  value: string | null;
  reason: string | null;
  sources: string[];
}}

export interface GeoComparisonEntry {{
  slug: string;
  values: Record<GeoComparisonAxis, GeoComparisonCell>;
}}

export interface GeoComparisonHub {{
  question: string;
  axes: GeoComparisonAxis[];
  entries: GeoComparisonEntry[];
  limits: string;
  source_note: string;
}}

export type GeoComparisons = Record<'graphrag' | 'gnn', GeoComparisonHub>;

export const GEO_COMPARISONS_SOURCE_SHA256 = '{digest}';
export const GEO_COMPARISONS: GeoComparisons = {payload};
"""


def projections(document: dict[str, Any]) -> dict[Path, str]:
    return {
        PYTHON_OUTPUT: _python_projection(document),
        TYPESCRIPT_OUTPUT: _typescript_projection(document),
    }


def sync(*, check: bool = False, source: Path = SOURCE) -> bool:
    expected = projections(load_source(source))
    stale = [
        path
        for path, content in expected.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]
    if check:
        for path in stale:
            try:
                display_path = path.relative_to(REPO_ROOT)
            except ValueError:
                display_path = path
            print(f"stale or missing generated projection: {display_path}", file=sys.stderr)
        return not stale
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of writing stale projections")
    parser.add_argument("--source", type=Path, default=SOURCE)
    args = parser.parse_args()
    try:
        return 0 if sync(check=args.check, source=args.source.resolve()) else 1
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"GEO comparison validation failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
