"""Generated by scripts/sync_geo_comparisons.py; do not edit."""

GEO_COMPARISONS_SOURCE_SHA256 = "59af32f98680e14bde48e23f7bd1202f52dcd476cb5329bd4c64b54f2783d5fd"
GEO_COMPARISONS = {'graphrag': {'question': '질문의 범위, 코퍼스 갱신 주기, 필요한 근거 추적 수준에 따라 어떤 GraphRAG 검색 설계가 맞는가?',
              'axes': ['retrieval_or_representation_unit',
                       'graph_construction',
                       'evaluation_context',
                       'traceability',
                       'cost',
                       'failure_conditions'],
              'entries': [{'slug': 'ms-graphrag-global-query-focused-summarization',
                           'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                           'value': '계층별 커뮤니티 보고서를 '
                                                                                    '질의와 대조해 부분 '
                                                                                    '답변을 만들고, 이를 '
                                                                                    'map-reduce로 '
                                                                                    '합쳐 코퍼스 전체의 '
                                                                                    '주제를 요약한다.',
                                                                           'reason': None,
                                                                           'sources': ['https://arxiv.org/pdf/2404.16130v2']},
                                      'graph_construction': {'state': 'known',
                                                             'value': 'LLM이 청크에서 엔티티·관계·주장을 추출하고, '
                                                                      'Leiden 커뮤니티 계층을 만든 뒤 하위에서 '
                                                                      '상위로 커뮤니티 보고서를 사전 생성한다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2404.16130v2']},
                                      'evaluation_context': {'state': 'known',
                                                             'value': '약 100만 토큰 Podcast와 약 170만 '
                                                                      '토큰 News 코퍼스의 global '
                                                                      'sensemaking 질문에서, LLM 판정으로 '
                                                                      '포괄성·다양성·empowerment·directness를 '
                                                                      '비교했다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2404.16130v2']},
                                      'traceability': {'state': 'known',
                                                       'value': '커뮤니티 보고서와 부분 답변은 추출 그래프와 원문 청크에서 '
                                                                '이어지지만, 최종 생성 답변 자체가 문장별 원문 근거를 '
                                                                '보증하지는 않는다.',
                                                       'reason': None,
                                                       'sources': ['https://arxiv.org/pdf/2404.16130v2']},
                                      'cost': {'state': 'known',
                                               'value': '색인 때 엔티티 추출과 계층 보고서 생성 비용을 먼저 지불한다. 같은 '
                                                        '코퍼스에 전역 질문이 반복되면 사전 생성 보고서를 재사용할 수 있지만, '
                                                        '질의 때도 보고서별 부분 답변과 통합 호출이 필요하다.',
                                               'reason': None,
                                               'sources': ['https://arxiv.org/pdf/2404.16130v2']},
                                      'failure_conditions': {'state': 'known',
                                                             'value': '국소 사실 조회에는 과한 경로가 될 수 있고, '
                                                                      '추출·엔티티 병합·다단계 요약 오류가 상위 '
                                                                      '보고서로 전파될 수 있다. 원문 평가는 두 영어 '
                                                                      '코퍼스와 LLM 판정에 한정되며 '
                                                                      'fabrication rate는 직접 비교하지 '
                                                                      '않았다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2404.16130v2']}}},
                          {'slug': 'lightrag-dual-level-graph-rag',
                           'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                           'value': '질문에서 만든 '
                                                                                    'low-level '
                                                                                    'key로 엔티티를, '
                                                                                    'high-level '
                                                                                    'key로 관계를 찾고, '
                                                                                    '관련 그래프 프로파일과 '
                                                                                    '원문 청크를 함께 '
                                                                                    '조합한다.',
                                                                           'reason': None,
                                                                           'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']},
                                      'graph_construction': {'state': 'known',
                                                             'value': 'LLM이 문서에서 엔티티와 관계 프로파일을 '
                                                                      '추출하고 중복을 합쳐 그래프를 만든다. 새 문서는 '
                                                                      '같은 추출 절차를 거쳐 기존 노드·엣지 집합에 '
                                                                      '증분 병합한다.',
                                                             'reason': None,
                                                             'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']},
                                      'evaluation_context': {'state': 'known',
                                                             'value': 'UltraDomain의 '
                                                                      'Agriculture·CS·Legal·Mix 네 '
                                                                      '코퍼스(약 60만~500만 토큰)에서 LLM 기반 '
                                                                      '포괄성·다양성·empowerment·overall '
                                                                      '비교와 ablation을 수행했다.',
                                                             'reason': None,
                                                             'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']},
                                      'traceability': {'state': 'known',
                                                       'value': '색인된 엔티티와 관계 프로파일은 원문 chunk ID를 '
                                                                '보존하고 검색 결과에 원문을 포함할 수 있다. 이 연결은 '
                                                                '확인 경로를 제공하지만 생성 답변의 사실성을 자동 보증하지 '
                                                                '않는다.',
                                                       'reason': None,
                                                       'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']},
                                      'cost': {'state': 'known',
                                               'value': 'Legal 데이터 조건에서 키워드 생성·검색 토큰과 API 호출, 증분 '
                                                        '갱신 비용을 GraphRAG와 비교했다. 전체 그래프 재구축을 피하는 '
                                                        '장점은 있지만 절대 비용은 추출 모델과 코퍼스에 따라 다시 측정해야 한다.',
                                               'reason': None,
                                               'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']},
                                      'failure_conditions': {'state': 'known',
                                                             'value': 'low-level만 쓰면 넓은 관계를 놓치고 '
                                                                      'high-level만 쓰면 정밀한 답이 약해지는 '
                                                                      'ablation 결과가 있다. 보고된 비용·품질 '
                                                                      '비교는 선택한 네 코퍼스와 LLM 평가 설정 '
                                                                      '밖으로 그대로 일반화할 수 없다.',
                                                             'reason': None,
                                                             'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']}}},
                          {'slug': 'deep-graphrag',
                           'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                           'value': '상위 커뮤니티에서 시작해 '
                                                                                    '관련 하위 그래프와 '
                                                                                    '엔티티로 좁혀 가는 '
                                                                                    '3단계 '
                                                                                    'global-to-local '
                                                                                    '검색이며, 고정 폭 '
                                                                                    'beam search와 '
                                                                                    '문맥 재랭킹을 쓴다.',
                                                                           'reason': None,
                                                                           'sources': ['https://arxiv.org/pdf/2601.11144v3']},
                                      'graph_construction': {'state': 'known',
                                                             'value': '600토큰 청크와 100토큰 겹침을 사용하고, '
                                                                      '엔티티 설명 임베딩 정합 뒤 재귀 '
                                                                      'Louvain으로 커뮤니티 계층을 구성한다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2601.11144v3']},
                                      'evaluation_context': {'state': 'known',
                                                             'value': 'Natural Questions와 '
                                                                      'HotpotQA를 '
                                                                      'local·global·comprehensive '
                                                                      '질문으로 나눠 Exact Match를 비교했고, '
                                                                      'NQ에서 Local Search·DRIFT와 '
                                                                      '지연시간을 비교했다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2601.11144v3']},
                                      'traceability': {'state': 'unknown',
                                                       'value': None,
                                                       'reason': '논문은 검색된 엔티티·하위 그래프를 최종 답변의 원문 '
                                                                 '구절이나 사용자용 인용으로 연결하는 규약을 보고하지 '
                                                                 '않는다.',
                                                       'sources': ['https://arxiv.org/pdf/2601.11144v3']},
                                      'cost': {'state': 'known',
                                               'value': 'NQ에서 DRIFT 대비 local/global 질문 지연 감소와 1.5B '
                                                        '통합 모델의 조건부 성능을 보고한다. 그래프 구축, 재랭킹, '
                                                        '증류·DW-GRPO 훈련을 합친 총비용 비교는 제공하지 않는다.',
                                               'reason': None,
                                               'sources': ['https://arxiv.org/pdf/2601.11144v3']},
                                      'failure_conditions': {'state': 'known',
                                                             'value': '계층 요약이 comprehensive 질문의 세부 '
                                                                      '사실을 가릴 수 있으며, 원문도 일부 CQ에서 '
                                                                      'local search가 앞선 사례를 인정한다. '
                                                                      '근거는 두 QA 데이터셋과 단일 계층·beam '
                                                                      '설정에 묶인다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2601.11144v3']}}}],
              'limits': '세 논문은 질문 유형, 코퍼스, 평가 지표와 생성 모델이 다르다. 표의 목적은 승자를 정하는 것이 아니라 반복 전역 요약, 증분 '
                        '갱신, 계층적 global-to-local 검색 중 어떤 조건이 필요한지 구분하는 데 있다.',
              'source_note': '각 셀은 해당 방법의 원논문 PDF에 근거한다. 비용은 논문이 공개한 조건 안에서만 정성적으로 서술했으며, 보고되지 않은 '
                             '총비용과 사용자용 인용 기능은 추정하지 않았다.'},
 'gnn': {'question': '예측 단위, 새 노드 대응, 설명 필요성, 공정한 기준선 조건에 따라 어떤 GNN 계열 방법을 먼저 검토해야 하는가?',
         'axes': ['retrieval_or_representation_unit',
                  'graph_construction',
                  'evaluation_context',
                  'traceability',
                  'cost',
                  'failure_conditions'],
         'entries': [{'slug': 'semi-supervised-classification-graph-convolutional-networks-review-2026',
                      'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                      'value': '주어진 그래프의 인접행렬과 노드 '
                                                                               '특징을 정규화된 이웃 집계로 '
                                                                               '전파해 노드별 표현과 분류값을 '
                                                                               '만든다.',
                                                                      'reason': None,
                                                                      'sources': ['https://arxiv.org/pdf/1609.02907']},
                                 'graph_construction': {'state': 'not_applicable',
                                                        'value': None,
                                                        'reason': 'GCN은 입력 그래프의 인접행렬을 전제로 하며, 원시 '
                                                                  '데이터에서 그래프를 만드는 절차를 제안하지 않는다.',
                                                        'sources': ['https://arxiv.org/pdf/1609.02907']},
                                 'evaluation_context': {'state': 'known',
                                                        'value': '고정된 citation·knowledge graph에서 '
                                                                 '준지도 노드 분류를 평가하고, 전체 그래프를 한 번에 쓰는 '
                                                                 'full-batch 설정을 사용했다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1609.02907']},
                                 'traceability': {'state': 'not_applicable',
                                                  'value': None,
                                                  'reason': '이 논문은 예측 표현 학습이 목적이며, 개별 예측에 대한 '
                                                            '부분그래프·특징 설명 절차를 포함하지 않는다.',
                                                  'sources': ['https://arxiv.org/pdf/1609.02907']},
                                 'cost': {'state': 'known',
                                          'value': '희소 인접행렬을 쓰면 한 층의 계산과 메모리가 엣지 수에 선형이지만, 논문 구현은 '
                                                   '데이터가 메모리에 들어가는 full-batch 학습을 전제로 한다.',
                                          'reason': None,
                                          'sources': ['https://arxiv.org/pdf/1609.02907']},
                                 'failure_conditions': {'state': 'known',
                                                        'value': '고정 그래프와 full-batch 조건에 묶이며, 새 '
                                                                 '노드·새 그래프를 즉시 처리하는 inductive 절차와 '
                                                                 '대규모 mini-batch 확장은 원문 범위 밖이다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1609.02907']}}},
                     {'slug': 'graphsage-inductive-representation-learning-large-graphs-review-2026',
                      'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                      'value': '대상 노드의 고정 수 이웃을 '
                                                                               '샘플링하고 층별 '
                                                                               'aggregator로 이웃 특징을 '
                                                                               '합쳐, 보지 못한 노드에도 적용할 '
                                                                               '수 있는 표현 함수를 학습한다.',
                                                                      'reason': None,
                                                                      'sources': ['https://arxiv.org/pdf/1706.02216']},
                                 'graph_construction': {'state': 'not_applicable',
                                                        'value': None,
                                                        'reason': 'GraphSAGE는 '
                                                                  'citation·Reddit·PPI처럼 이미 정의된 '
                                                                  '그래프와 노드 특징을 사용하며 그래프 생성 자체를 다루지 '
                                                                  '않는다.',
                                                        'sources': ['https://arxiv.org/pdf/1706.02216']},
                                 'evaluation_context': {'state': 'known',
                                                        'value': '시간 뒤의 citation·Reddit 노드와 완전히 보지 '
                                                                 '못한 PPI 그래프를 대상으로 inductive node '
                                                                 'classification을 평가했다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1706.02216']},
                                 'traceability': {'state': 'not_applicable',
                                                  'value': None,
                                                  'reason': '샘플링된 이웃은 계산 입력이지만, 원 논문은 이를 예측 근거 '
                                                            '설명이나 인과적 증거로 검증하지 않는다.',
                                                  'sources': ['https://arxiv.org/pdf/1706.02216']},
                                 'cost': {'state': 'known',
                                          'value': '이웃 샘플 수로 계산량을 제한해 정확도와 실행시간을 조절한다. 큰 샘플은 수익이 '
                                                   '줄고, 깊이가 늘면 필요한 다중-hop 이웃 수가 곱으로 커질 수 있다.',
                                          'reason': None,
                                          'sources': ['https://arxiv.org/pdf/1706.02216']},
                                 'failure_conditions': {'state': 'known',
                                                        'value': '표현 품질은 사용할 수 있는 노드 특징과 이웃 샘플에 '
                                                                 '의존한다. 원문은 uniform sampling을 사용하며 '
                                                                 'directed·multi-modal graph와 학습형 '
                                                                 'sampling은 후속 과제로 남긴다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1706.02216']}}},
                     {'slug': 'gnnexplainer-gnn-subgraph-feature-mask-review-2026',
                      'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                      'value': '학습된 GNN의 특정 예측을 '
                                                                               '유지하는 작은 '
                                                                               'computation '
                                                                               'subgraph와 '
                                                                               'node-feature mask를 '
                                                                               '사후 최적화한다.',
                                                                      'reason': None,
                                                                      'sources': ['https://arxiv.org/pdf/1903.03894v4']},
                                 'graph_construction': {'state': 'not_applicable',
                                                        'value': None,
                                                        'reason': '설명 대상 GNN과 그 입력 그래프를 고정한 뒤 '
                                                                  'mask를 찾는 방법이므로 새 그래프를 구성하지 않는다.',
                                                        'sources': ['https://arxiv.org/pdf/1903.03894v4']},
                                 'evaluation_context': {'state': 'known',
                                                        'value': '정답 motif가 심어진 synthetic '
                                                                 'node-classification graph와 '
                                                                 'MUTAG·REDDIT-BINARY graph '
                                                                 'classification 사례에서 설명을 평가했다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1903.03894v4']},
                                 'traceability': {'state': 'known',
                                                  'value': '예측에 민감한 edge와 feature를 mask로 제시해 모델 '
                                                           '내부의 사용 신호를 검사할 수 있다. 이 mask는 현실 세계의 인과 '
                                                           '원인이나 개입 효과를 뜻하지 않는다.',
                                                  'reason': None,
                                                  'sources': ['https://arxiv.org/pdf/1903.03894v4']},
                                 'cost': {'state': 'known',
                                          'value': '각 설명마다 연속 mask를 gradient optimization으로 찾아야 '
                                                   '하며, 후보 subgraph의 직접 조합 탐색을 피하는 대신 설명별 최적화 비용이 '
                                                   '든다.',
                                          'reason': None,
                                          'sources': ['https://arxiv.org/pdf/1903.03894v4']},
                                 'failure_conditions': {'state': 'known',
                                                        'value': '설명 크기·feature 수·regularization '
                                                                 '설정에 민감하고, synthetic 평가는 미리 심은 '
                                                                 'motif를 기준으로 한다. 여러 mask가 같은 예측을 '
                                                                 '보존할 수 있어 유일한 원인 설명으로 읽을 수 없다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1903.03894v4']}}},
                     {'slug': 'classic-gnns-strong-baselines-graph-level-tasks-gnnplus-review-2026',
                      'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                      'value': 'GCN·GIN·GatedGCN의 '
                                                                               'message passing에 '
                                                                               'edge feature, '
                                                                               'normalization, '
                                                                               'dropout, residual '
                                                                               'connection, FFN, '
                                                                               'positional '
                                                                               'encoding을 결합해 node '
                                                                               'representation을 '
                                                                               '만든다. '
                                                                               'graph-level/property '
                                                                               '과제에서는 이를 pooling해 '
                                                                               'graph '
                                                                               'representation으로 '
                                                                               '바꾸고, '
                                                                               'PATTERN·CLUSTER·PascalVOC-SP·COCO-SP에서는 '
                                                                               'node-level 출력을 '
                                                                               '유지한다.',
                                                                      'reason': None,
                                                                      'sources': ['https://arxiv.org/html/2502.09263v3']},
                                 'graph_construction': {'state': 'not_applicable',
                                                        'value': None,
                                                        'reason': 'GNN+는 주어진 분자·superpixel·code '
                                                                  'graph 등의 학습 블록과 튜닝 기준선이며, 그래프 '
                                                                  '구축 절차를 제안하지 않는다.',
                                                        'sources': ['https://arxiv.org/abs/2502.09263v3']},
                                 'evaluation_context': {'state': 'known',
                                                        'value': '논문의 graph-level study가 묶은 14개 '
                                                                 '벤치마크에서 세 classic GNN 변형을 재평가했다. '
                                                                 '이 가운데 10개는 graph-level/property '
                                                                 'prediction이고, '
                                                                 'PATTERN·CLUSTER·PascalVOC-SP·COCO-SP '
                                                                 '네 개는 node classification이다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/html/2502.09263v3']},
                                 'traceability': {'state': 'not_applicable',
                                                  'value': None,
                                                  'reason': '이 연구는 강한 예측 기준선 구축이 목적이며, 개별 graph '
                                                            'prediction의 근거를 설명하는 별도 메커니즘을 포함하지 '
                                                            '않는다.',
                                                  'sources': ['https://arxiv.org/abs/2502.09263v3']},
                                 'cost': {'state': 'known',
                                          'value': '논문은 여러 데이터셋에서 Graph Transformer보다 빠른 실행을 '
                                                   '보고하지만, 이 비교는 선택한 모델·데이터셋·튜닝 조건에 한정된다.',
                                          'reason': None,
                                          'sources': ['https://arxiv.org/abs/2502.09263v3']},
                                 'failure_conditions': {'state': 'known',
                                                        'value': '성능은 edge feature, positional '
                                                                 'encoding, FFN과 데이터셋별 탐색을 포함한 조합에 '
                                                                 '의존한다. 장거리 의존성과 '
                                                                 'over-smoothing·over-squashing이 '
                                                                 '모든 그래프에서 해결됐다는 근거는 아니다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/abs/2502.09263v3']}}}],
         'limits': '네 항목은 같은 문제의 순위표가 아니다. GCN·GraphSAGE·GNN+는 서로 다른 예측·일반화 조건을 다루고, GNNExplainer는 '
                   '이미 학습된 모델을 설명하는 사후 방법이다.',
         'source_note': '각 셀은 원논문 PDF 또는 공식 arXiv 버전에 근거한다. 입력 그래프를 전제로 하는 방법의 graph_construction과 '
                        '설명 기능이 없는 예측 모델의 traceability는 not_applicable로 구분했다.'}}
