"""Generated by scripts/sync_geo_comparisons.py; do not edit."""

GEO_COMPARISONS_SOURCE_SHA256 = "58b7ef348d353e4b22eff2ffd4f1157cce0a15a36db0f8c62f300156a44aae2f"
GEO_COMPARISONS = {'graphrag': {'question': '11편 가운데 전역 요약, 엔티티·관계 이중 검색, 계층 검색을 보여 주는 세 설계를 비교합니다. 질문 범위와 갱신 방식, 원문 '
                          '근거 확인 경로를 먼저 구분하고, 서로 다른 평가 조건의 결과는 순위로 합치지 않습니다.',
              'reading_guide': [{'title': '1–3 · 문서 탐색에서 전역 요약과 기억으로',
                                 'slugs': ['knowledge-graph-prompting-multi-document-qa',
                                           'ms-graphrag-global-query-focused-summarization',
                                           'hipporag-neurobiologically-inspired-long-term-memory'],
                                 'description': 'KGP → MS GraphRAG → HippoRAG 순서로 문서 간 연결을 탐색하고, '
                                                '커뮤니티 보고서로 전체를 요약하며, 그래프를 연상 기억으로 쓰는 관점을 구분합니다. '
                                                '커뮤니티는 연결이 조밀한 엔티티 묶음이고, map-reduce는 부분 답변을 만든 뒤 '
                                                '하나로 합치는 처리입니다.'},
                                {'title': '4–6 · 검색 단위와 기억·경로의 차이',
                                 'slugs': ['lightrag-dual-level-graph-rag',
                                           'hipporag2-from-rag-to-memory',
                                           'causalrag-causal-graph-retrieval'],
                                 'description': 'LightRAG → HippoRAG 2 → CausalRAG로 엔티티·관계 이중 검색, '
                                                '장기 기억, 인과 경로 검색을 읽습니다. 무엇을 색인하고 어떤 연결을 검색하는지 먼저 '
                                                '비교합니다.'},
                                {'title': '7–9 · 집약·선형화·계층 검색',
                                 'slugs': ['leanrag-semantic-aggregation-hierarchical-retrieval',
                                           'linearrag-linear-graph-retrieval-augmented-generation',
                                           'deep-graphrag'],
                                 'description': 'LeanRAG → LinearRAG → Deep GraphRAG로 그래프를 집약하거나 '
                                                '단순화하고, 계층을 따라 검색하는 설계를 살펴봅니다. 검색 결과를 통합하는 단계와 최종 '
                                                '답변을 생성하는 단계를 분리해 읽습니다.'},
                                {'title': '10–11 · 게이트와 전체 파이프라인 점검',
                                 'slugs': ['causalrag2-hugrag-hierarchical-causal-gating', 'ragu'],
                                 'description': 'CausalRAG2 → RAGU로 계층형 인과 게이트와 다단계 파이프라인을 읽고 '
                                                '추출·색인·검색·생성의 비용과 오류 경로를 돌아봅니다. LLM 판정과 정답 문자열 '
                                                '일치(Exact Match)는 같은 평가 지표가 아닙니다.'}],
              'axes': ['retrieval_or_representation_unit',
                       'graph_construction',
                       'evaluation_context',
                       'traceability',
                       'cost',
                       'failure_conditions'],
              'entries': [{'slug': 'ms-graphrag-global-query-focused-summarization',
                           'label': 'MS GraphRAG',
                           'summary': {'role': '문서 집합 전체를 요약하는 검색 설계',
                                       'fit': '여러 문서에 흩어진 공통 주제와 흐름을 묻는 경우',
                                       'caution': '색인·요약 비용이 들며 국소 사실 조회의 우위를 뜻하지 않습니다.'},
                           'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                           'value': '계층별 커뮤니티 보고서를 '
                                                                                    '질의와 대조해 부분 '
                                                                                    '답변을 만들고, 이를 '
                                                                                    'map-reduce로 '
                                                                                    '합쳐 코퍼스 전체의 '
                                                                                    '주제를 요약한다.',
                                                                           'reason': None,
                                                                           'sources': ['https://arxiv.org/pdf/2404.16130v2']},
                                      'graph_construction': {'state': 'known',
                                                             'value': 'LLM이 청크에서 엔티티·관계·주장을 추출하고, '
                                                                      'Leiden 커뮤니티 계층을 만든 뒤 하위에서 '
                                                                      '상위로 커뮤니티 보고서를 사전 생성한다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2404.16130v2']},
                                      'evaluation_context': {'state': 'known',
                                                             'value': '약 100만 토큰 Podcast와 약 170만 '
                                                                      '토큰 News 코퍼스의 global '
                                                                      'sensemaking 질문에서, LLM 판정으로 '
                                                                      '포괄성·다양성·empowerment·directness를 '
                                                                      '비교했다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2404.16130v2']},
                                      'traceability': {'state': 'known',
                                                       'value': '커뮤니티 보고서와 부분 답변은 추출 그래프와 원문 청크에서 '
                                                                '이어지지만, 최종 생성 답변 자체가 문장별 원문 근거를 '
                                                                '보증하지는 않는다.',
                                                       'reason': None,
                                                       'sources': ['https://arxiv.org/pdf/2404.16130v2']},
                                      'cost': {'state': 'known',
                                               'value': '색인 때 엔티티 추출과 계층 보고서 생성 비용을 먼저 지불한다. 같은 '
                                                        '코퍼스에 전역 질문이 반복되면 사전 생성 보고서를 재사용할 수 있지만, '
                                                        '질의 때도 보고서별 부분 답변과 통합 호출이 필요하다.',
                                               'reason': None,
                                               'sources': ['https://arxiv.org/pdf/2404.16130v2']},
                                      'failure_conditions': {'state': 'known',
                                                             'value': '국소 사실 조회에는 과한 경로가 될 수 있고, '
                                                                      '추출·엔티티 병합·다단계 요약 오류가 상위 '
                                                                      '보고서로 전파될 수 있다. 원문 평가는 두 영어 '
                                                                      '코퍼스와 LLM 판정에 한정되며 '
                                                                      'fabrication rate는 직접 비교하지 '
                                                                      '않았다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2404.16130v2']}}},
                          {'slug': 'lightrag-dual-level-graph-rag',
                           'label': 'LightRAG',
                           'summary': {'role': '엔티티와 관계를 함께 찾는 이중 검색',
                                       'fit': '구체적 대상과 넓은 관계를 함께 찾고 문서를 증분 갱신하는 경우',
                                       'caution': '추출 오류가 검색에 영향을 주며 총비용은 사용 조건에 따라 다릅니다.'},
                           'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                           'value': '질문에서 만든 '
                                                                                    'low-level '
                                                                                    'key로 엔티티를, '
                                                                                    'high-level '
                                                                                    'key로 관계를 찾고, '
                                                                                    '관련 그래프 프로파일과 '
                                                                                    '원문 청크를 함께 '
                                                                                    '조합한다.',
                                                                           'reason': None,
                                                                           'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']},
                                      'graph_construction': {'state': 'known',
                                                             'value': 'LLM이 문서에서 엔티티와 관계 프로파일을 '
                                                                      '추출하고 중복을 합쳐 그래프를 만든다. 새 문서는 '
                                                                      '같은 추출 절차를 거쳐 기존 노드·엣지 집합에 '
                                                                      '증분 병합한다.',
                                                             'reason': None,
                                                             'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']},
                                      'evaluation_context': {'state': 'known',
                                                             'value': 'UltraDomain의 '
                                                                      'Agriculture·CS·Legal·Mix 네 '
                                                                      '코퍼스(약 60만~500만 토큰)에서 LLM 기반 '
                                                                      '포괄성·다양성·empowerment·overall '
                                                                      '비교와 ablation을 수행했다.',
                                                             'reason': None,
                                                             'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']},
                                      'traceability': {'state': 'known',
                                                       'value': '색인된 엔티티와 관계 프로파일은 원문 chunk ID를 '
                                                                '보존하고 검색 결과에 원문을 포함할 수 있다. 이 연결은 '
                                                                '확인 경로를 제공하지만 생성 답변의 사실성을 자동 보증하지 '
                                                                '않는다.',
                                                       'reason': None,
                                                       'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']},
                                      'cost': {'state': 'known',
                                               'value': 'Legal 데이터 조건에서 키워드 생성·검색 토큰과 API 호출, 증분 '
                                                        '갱신 비용을 GraphRAG와 비교했다. 전체 그래프 재구축을 피하는 '
                                                        '장점은 있지만 절대 비용은 추출 모델과 코퍼스에 따라 다시 측정해야 한다.',
                                               'reason': None,
                                               'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']},
                                      'failure_conditions': {'state': 'known',
                                                             'value': 'low-level만 쓰면 넓은 관계를 놓치고 '
                                                                      'high-level만 쓰면 정밀한 답이 약해지는 '
                                                                      'ablation 결과가 있다. 보고된 비용·품질 '
                                                                      '비교는 선택한 네 코퍼스와 LLM 평가 설정 '
                                                                      '밖으로 그대로 일반화할 수 없다.',
                                                             'reason': None,
                                                             'sources': ['https://aclanthology.org/2025.findings-emnlp.568.pdf']}}},
                          {'slug': 'deep-graphrag',
                           'label': 'Deep GraphRAG',
                           'summary': {'role': '계층 검색과 지식 통합을 결합하는 파이프라인',
                                       'fit': '넓은 문맥에서 세부 근거로 내려가는 검색을 검토하는 경우',
                                       'caution': '작은 통합 모델과 별도의 최종 생성 모델을 구분해야 합니다.'},
                           'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                           'value': '상위 커뮤니티에서 시작해 '
                                                                                    '관련 하위 그래프와 '
                                                                                    '엔티티로 좁혀 가는 '
                                                                                    '3단계 '
                                                                                    'global-to-local '
                                                                                    '검색이며, 고정 폭 '
                                                                                    'beam search와 '
                                                                                    '문맥 재랭킹을 쓴다.',
                                                                           'reason': None,
                                                                           'sources': ['https://arxiv.org/pdf/2601.11144v3']},
                                      'graph_construction': {'state': 'known',
                                                             'value': '600토큰 청크와 100토큰 겹침을 사용하며, '
                                                                      'Qwen2.5-72B-Instruct로 엔티티와 '
                                                                      '방향성 관계를 추출한다. 설명 임베딩으로 병합 '
                                                                      '후보를 찾고 LLM으로 동일 개체인지 확인한 뒤, '
                                                                      '재귀 Louvain으로 커뮤니티 계층을 구성한다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2601.11144v3']},
                                      'evaluation_context': {'state': 'known',
                                                             'value': 'Natural Questions와 '
                                                                      'HotpotQA를 '
                                                                      'local·global·comprehensive '
                                                                      '질문으로 나눠 Exact Match를 비교했고, '
                                                                      'NQ에서 Local Search·DRIFT와 '
                                                                      '지연시간을 비교했다. Table 1의 '
                                                                      '1.5B-DW-GRPO 모델은 지식 통합 단계에 '
                                                                      '쓰이며, 최종 답변 생성에는 별도의 '
                                                                      'Qwen2.5-72B 또는 DeepSeek-R1을 '
                                                                      '사용한다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2601.11144v3']},
                                      'traceability': {'state': 'unknown',
                                                       'value': None,
                                                       'reason': '논문은 검색된 엔티티·하위 그래프를 최종 답변의 원문 '
                                                                 '구절이나 사용자용 인용으로 연결하는 규약을 보고하지 '
                                                                 '않는다.',
                                                       'sources': ['https://arxiv.org/pdf/2601.11144v3']},
                                      'cost': {'state': 'known',
                                               'value': 'NQ에서 DRIFT 대비 local/global 질문 지연 감소를 '
                                                        '보고한다. 작은 통합 모델도 별도의 최종 생성 모델을 사용하며, 그래프 '
                                                        '추출·재랭킹·증류와 DW-GRPO 학습을 포함한 전체 비용 비교는 제공하지 '
                                                        '않는다.',
                                               'reason': None,
                                               'sources': ['https://arxiv.org/pdf/2601.11144v3']},
                                      'failure_conditions': {'state': 'known',
                                                             'value': '계층 요약이 comprehensive 질문의 세부 '
                                                                      '사실을 가릴 수 있으며, 원문도 일부 CQ에서 '
                                                                      'local search가 앞선 사례를 인정한다. '
                                                                      '근거는 두 QA 데이터셋과 단일 계층·beam '
                                                                      '설정에 묶인다.',
                                                             'reason': None,
                                                             'sources': ['https://arxiv.org/pdf/2601.11144v3']}}}],
              'limits': '세 논문은 질문 유형, 코퍼스, 평가 지표와 생성 모델이 다르다. 표의 목적은 승자를 정하는 것이 아니라 반복 전역 요약, 증분 '
                        '갱신, 계층적 global-to-local 검색 중 어떤 조건이 필요한지 구분하는 데 있다.',
              'source_note': '각 셀은 해당 방법의 원논문 PDF에 근거한다. 검색·지식 통합·최종 생성 단계와 색인·학습·질의 비용을 구분해 읽어야 '
                             '한다. 비용은 논문이 공개한 조건 안에서만 정성적으로 서술했으며, 보고되지 않은 총비용과 사용자용 인용 기능은 추정하지 '
                             '않았다.'},
 'gnn': {'question': '11편 중 예측 모델, 새 노드 표현 학습, 사후 설명, 기준선 개선의 차이를 보여 주는 네 논문을 비교합니다. 서로 대체하는 네 모델이 '
                     '아니라 목적에 따라 함께 검토할 연구입니다.',
         'reading_guide': [{'title': '1–2 · 노드를 벡터로 표현하기',
                            'slugs': ['deepwalk-online-learning-social-representations-review-2026',
                                      'structural-deep-network-embedding-sdne-review-2026'],
                            'description': 'DeepWalk·SDNE로 그래프의 노드를 어떻게 벡터로 표현하는지 익힙니다. 다음 단계에서는 '
                                           '노드 표현 자체를 학습하는 관점에서 특징과 이웃으로 표현을 계산하는 방식으로 이동합니다.'},
                           {'title': '3–6 · 이웃 집계·일반화·표현력',
                            'slugs': ['semi-supervised-classification-graph-convolutional-networks-review-2026',
                                      'graphsage-inductive-representation-learning-large-graphs-review-2026',
                                      'graph-attention-networks-gat-review-2026',
                                      'how-powerful-are-graph-neural-networks-gin-review-2026'],
                            'description': 'GCN·GraphSAGE·GAT·GIN으로 이웃 정보를 모으는 메시지 패싱, 새 노드에 적용하는 '
                                           '조건, 구조를 구별하는 능력을 살펴봅니다. 준지도 학습, 귀납적 적용, 어텐션, 표현력은 서로 '
                                           '다른 질문이며 귀납적 적용은 비지도 학습과 동의어가 아닙니다.'},
                           {'title': '7–8 · 노드와 관계의 종류 구분하기',
                            'slugs': ['heterogeneous-graph-neural-network-hetgnn-review-2026',
                                      'heterogeneous-graph-attention-network-han-review-2026'],
                            'description': 'HetGNN·HAN으로 노드와 관계의 종류가 다를 때 무엇을 구분해야 하는지 읽습니다. 단일 '
                                           '종류의 이웃 집계에서 타입과 관계 경로를 고려하는 입력 구조로 범위를 넓힙니다.'},
                           {'title': '9–10 · 이미 나온 예측 설명하기',
                            'slugs': ['gnnexplainer-gnn-subgraph-feature-mask-review-2026',
                                      'explaining-temporal-graph-neural-networks-feature-induced-information-flow-review-2026'],
                            'description': 'GNNExplainer·Temporal GNN 설명으로 예측에 관여한 입력 구조와 특징을 '
                                           '조사합니다. 마스크는 연결이나 특징을 선택·가중하는 값으로, 현실 인과를 증명하지 않습니다. 예측 '
                                           '모델을 만드는 문제와 그 판단을 설명하는 문제를 구분합니다.'},
                           {'title': '11 · 충분히 조정한 기준선과 비교하기',
                            'slugs': ['classic-gnns-strong-baselines-graph-level-tasks-gnnplus-review-2026'],
                            'description': 'GNN+로 새 모델의 성능을 주장하기 전에 기존 기준선을 충분히 조정했는지 돌아봅니다. 앞서 본 '
                                           '모델 구조를 실제 학습·평가 조건과 연결하되, 예측 출력 단위와 데이터 구성·분할 단위를 '
                                           '구분합니다.'}],
         'axes': ['retrieval_or_representation_unit',
                  'graph_construction',
                  'evaluation_context',
                  'traceability',
                  'cost',
                  'failure_conditions'],
         'entries': [{'slug': 'semi-supervised-classification-graph-convolutional-networks-review-2026',
                      'label': 'GCN',
                      'summary': {'role': '이웃 특징을 모아 예측하는 기본 모델',
                                  'fit': '고정된 그래프의 준지도 노드 분류를 이해하려는 경우',
                                  'caution': '원문의 실험 조건을 모든 GCN의 적용 한계로 일반화하지 않습니다.'},
                      'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                      'value': '이웃 특징을 집계하는 예측 '
                                                                               '아키텍처다. 주어진 그래프의 '
                                                                               '인접행렬과 노드 특징을 정규화된 '
                                                                               '이웃 집계로 전파해 노드별 표현과 '
                                                                               '분류값을 만든다.',
                                                                      'reason': None,
                                                                      'sources': ['https://arxiv.org/pdf/1609.02907']},
                                 'graph_construction': {'state': 'not_applicable',
                                                        'value': None,
                                                        'reason': 'GCN은 입력 그래프의 인접행렬을 전제로 하며, 원시 '
                                                                  '데이터에서 그래프를 만드는 절차를 제안하지 않는다.',
                                                        'sources': ['https://arxiv.org/pdf/1609.02907']},
                                 'evaluation_context': {'state': 'known',
                                                        'value': '고정된 citation·knowledge graph에서 '
                                                                 '준지도 노드 분류를 평가하고, 전체 그래프를 한 번에 쓰는 '
                                                                 'full-batch 설정을 사용했다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1609.02907']},
                                 'traceability': {'state': 'not_applicable',
                                                  'value': None,
                                                  'reason': '이 논문은 예측 표현 학습이 목적이며, 개별 예측에 대한 '
                                                            '부분그래프·특징 설명 절차를 포함하지 않는다.',
                                                  'sources': ['https://arxiv.org/pdf/1609.02907']},
                                 'cost': {'state': 'known',
                                          'value': '희소 인접행렬을 쓰면 한 층의 계산과 메모리가 엣지 수에 선형이지만, 논문 구현은 '
                                                   '데이터가 메모리에 들어가는 full-batch 학습을 전제로 한다.',
                                          'reason': None,
                                          'sources': ['https://arxiv.org/pdf/1609.02907']},
                                 'failure_conditions': {'state': 'known',
                                                        'value': '원문의 실험은 고정 그래프와 full-batch 학습 '
                                                                 '조건이다. §7.2는 메모리 부담을 줄일 '
                                                                 'mini-batch 확장을 후속 과제로 논의한다. 새 '
                                                                 '노드·새 그래프에 대한 귀납적 적용은 이 실험으로 검증하지 '
                                                                 '않았으며, 이를 모든 GCN의 고유 제약으로 일반화하지 '
                                                                 '않는다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1609.02907']}}},
                     {'slug': 'graphsage-inductive-representation-learning-large-graphs-review-2026',
                      'label': 'GraphSAGE',
                      'summary': {'role': '새 노드의 표현도 계산하는 학습 프레임워크',
                                  'fit': '학습 때 보지 못한 노드나 그래프에 적용하는 설정을 검토할 때',
                                  'caution': '귀납적 적용은 지도·비지도 학습 목적과 별개의 조건입니다.'},
                      'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                      'value': '대상 노드의 고정 수 이웃을 '
                                                                               '샘플링하고 층별 '
                                                                               'aggregator로 이웃 특징을 '
                                                                               '합쳐, 보지 못한 노드에도 적용할 '
                                                                               '수 있는 표현 함수를 학습한다.',
                                                                      'reason': None,
                                                                      'sources': ['https://arxiv.org/pdf/1706.02216']},
                                 'graph_construction': {'state': 'not_applicable',
                                                        'value': None,
                                                        'reason': 'GraphSAGE는 '
                                                                  'citation·Reddit·PPI처럼 이미 정의된 '
                                                                  '그래프와 노드 특징을 사용하며 그래프 생성 자체를 다루지 '
                                                                  '않는다.',
                                                        'sources': ['https://arxiv.org/pdf/1706.02216']},
                                 'evaluation_context': {'state': 'known',
                                                        'value': '시간 뒤의 citation·Reddit 노드와 완전히 보지 '
                                                                 '못한 PPI 그래프를 대상으로 inductive node '
                                                                 'classification을 평가했다. 학습 때 없던 '
                                                                 '노드·그래프에 적용하는 귀납적 설정과 지도·비지도 학습 '
                                                                 '목적은 별개의 선택이며, 원문은 두 학습 목적을 모두 '
                                                                 '다룬다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1706.02216']},
                                 'traceability': {'state': 'not_applicable',
                                                  'value': None,
                                                  'reason': '샘플링된 이웃은 계산 입력이지만, 원 논문은 이를 예측 근거 '
                                                            '설명이나 인과적 증거로 검증하지 않는다.',
                                                  'sources': ['https://arxiv.org/pdf/1706.02216']},
                                 'cost': {'state': 'known',
                                          'value': '이웃 샘플 수로 계산량을 제한해 정확도와 실행시간을 조절한다. 큰 샘플은 수익이 '
                                                   '줄고, 깊이가 늘면 필요한 다중-hop 이웃 수가 곱으로 커질 수 있다.',
                                          'reason': None,
                                          'sources': ['https://arxiv.org/pdf/1706.02216']},
                                 'failure_conditions': {'state': 'known',
                                                        'value': '표현 품질은 사용할 수 있는 노드 특징과 이웃 샘플에 '
                                                                 '의존한다. 원문은 uniform sampling을 사용하며 '
                                                                 'directed·multi-modal graph와 학습형 '
                                                                 'sampling은 후속 과제로 남긴다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1706.02216']}}},
                     {'slug': 'gnnexplainer-gnn-subgraph-feature-mask-review-2026',
                      'label': 'GNNExplainer',
                      'summary': {'role': '학습된 모델의 예측을 조사하는 사후 설명',
                                  'fit': '특정 예측에 관여한 연결과 입력 특징을 살펴보려는 경우',
                                  'caution': '예측 모델의 대체재도, 현실 인과관계의 증명도 아닙니다.'},
                      'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                      'value': '이미 학습된 GNN의 특정 예측을 '
                                                                               '유지하는 작은 '
                                                                               'computation '
                                                                               'subgraph와 '
                                                                               'node-feature mask를 '
                                                                               '사후 최적화한다. 예측 모델을 '
                                                                               '대체하는 아키텍처가 아니라 그 '
                                                                               '판단을 조사하는 설명 방법이다.',
                                                                      'reason': None,
                                                                      'sources': ['https://arxiv.org/pdf/1903.03894v4']},
                                 'graph_construction': {'state': 'not_applicable',
                                                        'value': None,
                                                        'reason': '설명 대상 GNN과 그 입력 그래프를 고정한 뒤 '
                                                                  'mask를 찾는 방법이므로 새 그래프를 구성하지 않는다.',
                                                        'sources': ['https://arxiv.org/pdf/1903.03894v4']},
                                 'evaluation_context': {'state': 'known',
                                                        'value': '정답 motif가 심어진 synthetic '
                                                                 'node-classification graph와 '
                                                                 'MUTAG·REDDIT-BINARY graph '
                                                                 'classification 사례에서 설명을 평가했다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1903.03894v4']},
                                 'traceability': {'state': 'known',
                                                  'value': '예측에 민감한 edge와 feature를 mask로 제시해 모델 '
                                                           '내부의 사용 신호를 검사할 수 있다. 이 mask는 현실 세계의 인과 '
                                                           '원인이나 개입 효과를 뜻하지 않는다.',
                                                  'reason': None,
                                                  'sources': ['https://arxiv.org/pdf/1903.03894v4']},
                                 'cost': {'state': 'known',
                                          'value': '각 설명마다 연속 mask를 gradient optimization으로 찾아야 '
                                                   '하며, 후보 subgraph의 직접 조합 탐색을 피하는 대신 설명별 최적화 비용이 '
                                                   '든다.',
                                          'reason': None,
                                          'sources': ['https://arxiv.org/pdf/1903.03894v4']},
                                 'failure_conditions': {'state': 'known',
                                                        'value': '설명 크기·feature 수·regularization '
                                                                 '설정에 민감하고, synthetic 평가는 미리 심은 '
                                                                 'motif를 기준으로 한다. 여러 mask가 같은 예측을 '
                                                                 '보존할 수 있어 유일한 원인 설명으로 읽을 수 없다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/pdf/1903.03894v4']}}},
                     {'slug': 'classic-gnns-strong-baselines-graph-level-tasks-gnnplus-review-2026',
                      'label': 'GNN+',
                      'summary': {'role': '기존 GNN을 충분히 조정하는 기준선 프레임워크',
                                  'fit': '새 구조의 효과를 비교하기 전에 학습·평가 조건을 점검할 때',
                                  'caution': '데이터 분할 단위와 예측 출력 단위를 구분해서 읽어야 합니다.'},
                      'values': {'retrieval_or_representation_unit': {'state': 'known',
                                                                      'value': '기존 '
                                                                               'GCN·GIN·GatedGCN에 '
                                                                               '구조·학습 요소를 결합하고 '
                                                                               '조정하는 기준선 프레임워크다. '
                                                                               'message passing에 '
                                                                               'edge feature, '
                                                                               'normalization, '
                                                                               'dropout, residual '
                                                                               'connection, FFN, '
                                                                               'positional '
                                                                               'encoding을 결합해 node '
                                                                               'representation을 '
                                                                               '만든다. '
                                                                               'graph-level/property '
                                                                               '과제에서는 이를 pooling해 '
                                                                               'graph '
                                                                               'representation으로 '
                                                                               '바꾸고, '
                                                                               'PATTERN·CLUSTER·PascalVOC-SP·COCO-SP에서는 '
                                                                               'node-level 출력을 '
                                                                               '유지한다.',
                                                                      'reason': None,
                                                                      'sources': ['https://arxiv.org/abs/2502.09263v3']},
                                 'graph_construction': {'state': 'not_applicable',
                                                        'value': None,
                                                        'reason': 'GNN+는 주어진 분자·superpixel·code '
                                                                  'graph 등의 학습 블록과 튜닝 기준선이며, 그래프 '
                                                                  '구축 절차를 제안하지 않는다.',
                                                        'sources': ['https://arxiv.org/abs/2502.09263v3']},
                                 'evaluation_context': {'state': 'known',
                                                        'value': '논문의 graph-level study가 묶은 14개 '
                                                                 '벤치마크에서 세 classic GNN 변형을 재평가했다. '
                                                                 '이 가운데 10개는 graph-level/property '
                                                                 'prediction이고, '
                                                                 'PATTERN·CLUSTER·PascalVOC-SP·COCO-SP '
                                                                 '네 개는 node classification이다. 여기서 '
                                                                 'graph-level은 그래프 단위 데이터 구성·분할 '
                                                                 '설정도 포함하며, 예측 출력이 모두 그래프 하나당 하나라는 '
                                                                 '뜻은 아니다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/abs/2502.09263v3']},
                                 'traceability': {'state': 'not_applicable',
                                                  'value': None,
                                                  'reason': '이 연구는 강한 예측 기준선 구축이 목적이며, 개별 graph '
                                                            'prediction의 근거를 설명하는 별도 메커니즘을 포함하지 '
                                                            '않는다.',
                                                  'sources': ['https://arxiv.org/abs/2502.09263v3']},
                                 'cost': {'state': 'known',
                                          'value': '논문은 여러 데이터셋에서 Graph Transformer보다 빠른 실행을 '
                                                   '보고하지만, 이 비교는 선택한 모델·데이터셋·튜닝 조건에 한정된다.',
                                          'reason': None,
                                          'sources': ['https://arxiv.org/abs/2502.09263v3']},
                                 'failure_conditions': {'state': 'known',
                                                        'value': '성능은 edge feature, positional '
                                                                 'encoding, FFN과 데이터셋별 탐색을 포함한 조합에 '
                                                                 '의존한다. 장거리 의존성과 '
                                                                 'over-smoothing·over-squashing이 '
                                                                 '모든 그래프에서 해결됐다는 근거는 아니다.',
                                                        'reason': None,
                                                        'sources': ['https://arxiv.org/abs/2502.09263v3']}}}],
         'limits': '네 항목은 같은 문제의 순위표가 아니다. GCN·GraphSAGE·GNN+는 서로 다른 예측·일반화 조건을 다루고, GNNExplainer는 '
                   '이미 학습된 모델을 설명하는 사후 방법이다.',
         'source_note': '각 항목은 원논문에 근거합니다. 입력 그래프를 새로 만드는 방법이 아니거나 예측을 설명하는 기능이 없는 경우에는 ‘해당 없음’으로 '
                        '표시했습니다. ‘미확인’은 논문에서 확인할 근거가 부족하다는 뜻입니다. 원문 실험의 제약을 모든 적용 상황의 한계로 일반화하지 '
                        '않으며, GNN의 예측 설명과 GraphRAG의 원문 근거 확인은 구분해서 읽어야 합니다.'}}
